version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: xlsx
      - dependency-name: kysely
    groups:
      all-npm:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "kysely"
          - "xlsx"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    groups:
      all-actions:
        patterns:
          - "*"
