version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      production-patch:
        dependency-type: production
        update-types: [patch]
      production-minor:
        dependency-type: production
        update-types: [minor]

  - package-ecosystem: npm
    directory: /e2e
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
