/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ArchiveProdCrm {
  ann_hardness: Numeric | null;
  coil_no: string;
  elongation_pct: Numeric | null;
  entry_id: Generated<Int8>;
  hardness_hrb: Numeric | null;
  hardness_vpn: Numeric | null;
  input_thk_mm: Numeric | null;
  loss_pct: Numeric | null;
  oil_consumption: Numeric | null;
  oil_level_final: Numeric | null;
  oil_level_initial: Numeric | null;
  output_thk_mm: Numeric | null;
  prod_date: Timestamp | null;
  remarks: string | null;
  roll_in: string | null;
  roll_out: string | null;
  rw_tension_kg: Numeric | null;
  scrap_mt: Numeric | null;
  shift_code: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  stretch_pct: Numeric | null;
  tenant_id: Generated<string>;
  time_from: string | null;
  time_to: string | null;
  tkg_weight_mt: Numeric | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
}

export interface ArchiveProdSkp {
  coil_no: string;
  coolant_press_kgcm2: Numeric | null;
  coolant_temp_degc: Numeric | null;
  entry_id: Generated<Int8>;
  final_thk_mm: Numeric | null;
  hold_mt: Numeric | null;
  prod_date: Timestamp | null;
  re_rolling: Generated<boolean | null>;
  rejection_mt: Numeric | null;
  remarks: string | null;
  rolls_in: string | null;
  rolls_out: string | null;
  rw_tension_kg: Numeric | null;
  shift_code: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  surface_finish: string | null;
  tenant_id: Generated<string>;
  thk_mm: Numeric | null;
  total_passes: number | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
  wt_reroll_mt: Numeric | null;
  wt_rolling_mt: Numeric | null;
  wt_scrap_mt: Numeric | null;
  wt_skinpass_mt: Numeric | null;
}

export interface ArchiveProdSkpPass {
  entry_id: Int8;
  pass_id: Generated<Int8>;
  pass_no: number;
  tenant_id: Generated<string>;
  thickness_mm: Numeric | null;
}

export interface AuditAuditLog {
  action: string;
  audit_id: Generated<Int8>;
  change_request_id: Int8 | null;
  column_name: string | null;
  new_value: string | null;
  old_value: string | null;
  record_pk: string;
  table_name: string;
  tenant_id: Generated<string>;
  ts: Generated<Timestamp>;
  user_id: number | null;
}

export interface AuditDprMonthLock {
  export_job_id: Int8 | null;
  finalized_at: Generated<Timestamp>;
  finalized_by: number | null;
  month: string;
}

export interface AuditExportJob {
  artifact_bytes: Int8 | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  data_version: string | null;
  error_message: string | null;
  export_id: Generated<Int8>;
  export_type: Generated<string>;
  file_path: string | null;
  format: string;
  generated_at: Timestamp | null;
  job_status: Generated<string>;
  params_json: Json | null;
  progress: Generated<number>;
  requested_by: number | null;
  row_count: number | null;
  scope: string;
  sha256: string | null;
  source_record_count: Int8 | null;
  storage_uri: string | null;
  tenant_id: Generated<string>;
}

export interface AuditLineageRef {
  batch_id: string | null;
  created_at: Generated<Timestamp>;
  mapping_version: string | null;
  record_id: string;
  source_row_ref: string | null;
  tenant_id: string;
}

export interface CanonEquipmentNode {
  asset_code: string;
  asset_id: Generated<string>;
  created_at: Generated<Timestamp>;
  name: string;
  process_code: string | null;
  tenant_id: string;
}

export interface CanonEvent {
  asset_id: string | null;
  category: string | null;
  created_at: Generated<Timestamp>;
  duration_min: number | null;
  ended_at: Timestamp | null;
  event_id: Generated<string>;
  event_type: string;
  lineage_ref: string;
  payload: Generated<Json>;
  started_at: Timestamp;
  tenant_id: string;
}

export interface CanonProductionCount {
  asset_id: string | null;
  count_id: Generated<string>;
  counted_at: Timestamp;
  created_at: Generated<Timestamp>;
  is_scrap: Generated<boolean>;
  lineage_ref: string;
  quantity: Numeric;
  shift_log_id: Int8 | null;
  tenant_id: string;
  uom: Generated<string>;
}

export interface CoilCoil {
  coil_no: string;
  coil_thk_mm: Numeric | null;
  coil_width_mm: Numeric | null;
  created_at: Generated<Timestamp>;
  current_process_id: number | null;
  customer_id: number | null;
  grade_code: string | null;
  heat_no: string | null;
  next_dest: string | null;
  nominal_width_mm: Numeric | null;
  parent_coil_no: string | null;
  status: Generated<string>;
  surface_finish: string | null;
  tenant_id: Generated<string>;
  weight_mt: Numeric | null;
}

export interface ConfigRulesetVersion {
  id: Generated<number>;
  published_at: Generated<Timestamp | null>;
  published_by: string | null;
  version: Generated<number>;
}

export interface ConfigValidationRule {
  field_id: string;
  is_active: Generated<boolean>;
  params: Json;
  rule_type: string;
  severity: string;
  updated_at: Generated<Timestamp | null>;
  updated_by: string | null;
}

export interface DprDailyEntry {
  created_at: Generated<Timestamp>;
  day_number: number;
  delay_data: Generated<Json>;
  field_provenance: Generated<Json>;
  id: Generated<string>;
  month_id: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  values: Generated<Json>;
}

export interface DprFieldMapping {
  adapter: string;
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  field_id: string;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DprMonth {
  config_overrides: Generated<Json>;
  created_at: Generated<Timestamp>;
  days_in_month: number;
  id: Generated<string>;
  month: number;
  sheet_code: string;
  status: Generated<string>;
  template_id: string;
  year: number;
}

export interface DprSourceMap {
  created_at: Generated<Timestamp>;
  field_id: string;
  id: Generated<string>;
  resolution_data: Generated<Json>;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface DprTemplate {
  blank_master_blob: Buffer;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  geometry_model: Json;
  id: Generated<string>;
  original_file_blob: Buffer | null;
}

export interface MasterCrmSubProcess {
  machine_code: string;
  name: string;
  sub_process_code: string;
}

export interface MasterCustomer {
  customer_code: string;
  customer_id: Generated<number>;
  customer_name: string;
  is_active: Generated<boolean>;
  tenant_id: Generated<string>;
}

export interface MasterDefectCode {
  applies_to: string | null;
  defect_code: string;
  description: string;
  is_active: Generated<boolean>;
  symbol: string | null;
  tenant_id: Generated<string>;
}

export interface MasterFurnace {
  code: string;
  furnace_id: number;
  furnace_type: Generated<string | null>;
  name: string | null;
  tenant_id: Generated<string>;
}

export interface MasterGrade {
  acid_pct_max: Numeric | null;
  acid_pct_min: Numeric | null;
  description: string | null;
  grade_code: string;
  grade_family: string | null;
  is_active: Generated<boolean>;
  pkl_speed_max: Numeric | null;
  pkl_speed_min: Numeric | null;
  tenant_id: Generated<string>;
}

export interface MasterGradeSpec {
  customer_id: number | null;
  elongation_pct_min: Numeric | null;
  grade_code: string;
  hardness_hrb_max: Numeric | null;
  hardness_hrb_min: Numeric | null;
  ra_um_max: Numeric | null;
  spec_id: Generated<number>;
  tenant_id: Generated<string>;
  uts_nmm2_max: Numeric | null;
  uts_nmm2_min: Numeric | null;
}

export interface MasterLineArea {
  area_code: string;
  dpr_area_label: string;
  is_dpr_reported: Generated<boolean>;
  name: string;
  operating_minutes_base: Generated<number>;
  process_code: string | null;
  sort_order: number;
}

export interface MasterMachine {
  capacity_mt: Numeric | null;
  department: string | null;
  machine_code: string;
  machine_status: Generated<string>;
  machine_type: Generated<string | null>;
  name: string;
  process_code: string | null;
  process_id: number | null;
}

export interface MasterMachineCrewRoster {
  created_at: Generated<Timestamp>;
  crew_id: Generated<Int8>;
  is_active: Generated<boolean>;
  machine_code: string;
  member_name: string;
  role_label: string;
  updated_at: Generated<Timestamp>;
}

export interface MasterOperator {
  emp_code: string;
  full_name: string;
  is_active: Generated<boolean>;
  operator_id: Generated<number>;
  tenant_id: Generated<string>;
}

export interface MasterProcess {
  code: string;
  has_mill_type: Generated<boolean>;
  name: string;
  process_id: number;
  seq_no: number;
  tenant_id: Generated<string>;
}

export interface MasterRouteCode {
  display_label: string;
  machine_code: string | null;
  process_code: string | null;
  route_code: string;
  seq_hint: Generated<number>;
  sub_process: string | null;
}

export interface MasterRpOilGrade {
  description: string | null;
  rp_oil_grade: string;
  tenant_id: Generated<string>;
}

export interface MasterShift {
  end_time: string;
  name: string;
  shift_code: string;
  start_time: string;
  tenant_id: Generated<string>;
}

export interface MasterStoppageCategory {
  agency_code: string | null;
  category_code: string;
  dpr_category: string | null;
  label: string;
  requires_breakdown_code: Generated<boolean>;
}

export interface MasterStoppageCode {
  agency_code: string | null;
  category: string;
  description: string;
  dpr_category: string | null;
  is_active: Generated<boolean>;
  is_planned: Generated<boolean>;
  stoppage_code: string;
  tenant_id: Generated<string>;
}

export interface MasterSurfaceFinish {
  description: string | null;
  surface_finish: string;
  tenant_id: Generated<string>;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface PgmigrationsM1 {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface PlanningCoilPlan {
  coil_no: string | null;
  coil_plan_id: Generated<Int8>;
  plan_order_id: Int8 | null;
  planned_date: Timestamp | null;
  planned_process_id: number | null;
  seq_no: number | null;
  tenant_id: Generated<string>;
}

export interface PlanningImportBatch {
  error_count: Generated<number | null>;
  errors_json: Json | null;
  file_name: string | null;
  import_batch_id: Generated<Int8>;
  imported_at: Generated<Timestamp>;
  imported_by: number | null;
  row_count: number | null;
  source: string;
  status: Generated<string>;
  tenant_id: Generated<string>;
}

export interface PlanningOrderJourney {
  coil_no: string;
  created_at: Generated<Timestamp>;
  current_step_no: Generated<number>;
  journey_id: Generated<Int8>;
  route_raw: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PlanningOrderJourneyStep {
  completed_at: Timestamp | null;
  display_label: string;
  journey_id: Int8;
  machine_code: string | null;
  process_code: string | null;
  queue_batch_id: Int8 | null;
  route_code: string;
  started_at: Timestamp | null;
  status: Generated<string>;
  step_id: Generated<Int8>;
  step_no: number;
  sub_process: string | null;
}

export interface PlanningPlanOrder {
  customer_id: number | null;
  due_date: Timestamp | null;
  grade_code: string | null;
  import_batch_id: Int8 | null;
  plan_order_id: Generated<Int8>;
  planned_qty_mt: Numeric | null;
  sap_order_no: string | null;
  surface_finish: string | null;
  target_thk_mm: Numeric | null;
  target_width_mm: Numeric | null;
  tenant_id: Generated<string>;
}

export interface PlanningPpcBatch {
  active_rolling_pass_no: Generated<number>;
  batch_id: Generated<Int8>;
  batch_number: string;
  coil_count: Generated<number | null>;
  coil_no: string;
  customer_name: string;
  destination: string | null;
  finish_thk_mm: Numeric | null;
  from_work_center: string | null;
  grade_code: string;
  import_batch_id: Int8 | null;
  import_remark: string | null;
  imported_at: Generated<Timestamp>;
  input_thk_mm: Numeric;
  item_no: string | null;
  machine_allocated: Generated<boolean>;
  machine_code: string;
  max_thk_tol_mm: Numeric | null;
  min_thk_tol_mm: Numeric | null;
  plan_date: Timestamp;
  ppc_remarks: string | null;
  ppc_reroll_flag: Generated<boolean | null>;
  ppc_thk_mm: Numeric;
  ppc_weight_mt: Numeric;
  process_route_canonical: string | null;
  process_route_raw: string | null;
  queue_seq: number | null;
  raw_row_json: Json | null;
  roll_finish: string | null;
  sap_order_no: string | null;
  shift_code: string;
  slit_id: string | null;
  sub_process: string;
  to_work_center: string | null;
  width_mm: Numeric;
}

export interface PlanningPpcRollingPassPlan {
  batch_id: Int8;
  is_required: Generated<boolean>;
  pass_no: number;
  plan_id: Generated<Int8>;
  roll_finish: string | null;
  target_thk_mm: Numeric | null;
}

export interface PlanningProductionTarget {
  area_code: string;
  created_at: Generated<Timestamp>;
  period: Timestamp;
  target_id: Generated<Int8>;
  target_mt: Numeric | null;
  target_rate: Numeric | null;
}

export interface PlanningQueueHandoff {
  created_at: Generated<Timestamp>;
  handoff_id: Generated<Int8>;
  journey_id: Int8;
  source: Generated<string>;
  source_step_id: Int8;
  target_batch_id: Int8 | null;
  target_step_no: number;
}

export interface SecurityAppUser {
  auth_subject: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  emp_code: string | null;
  full_name: string;
  pin_failed_attempts: Generated<number>;
  pin_hash: string | null;
  pin_locked_until: Timestamp | null;
  status: Generated<string>;
  tenant_id: Generated<string>;
  user_id: Generated<number>;
  username: string;
}

export interface SecurityDeviceRegistration {
  device_id: string;
  last_heartbeat: Timestamp | null;
  process_code: string;
  registered_at: Generated<Timestamp>;
  tenant_id: Generated<string>;
}

export interface SecurityLineAccess {
  access_level: Generated<string>;
  process_id: number;
  tenant_id: Generated<string>;
  user_id: number;
}

export interface SecurityMachineAccess {
  access_level: Generated<string>;
  assigned_at: Generated<Timestamp>;
  assigned_by: Int8 | null;
  machine_code: string;
  user_id: Int8;
}

export interface SecurityPermission {
  action: string;
  permission_id: Generated<Int8>;
  resource: string;
  role: string;
  tenant_id: string;
}

export interface SecurityRole {
  description: string | null;
  role_id: number;
  role_name: string;
  tenant_id: Generated<string>;
}

export interface SecurityTenant {
  created_at: Generated<Timestamp>;
  name: string;
  status: Generated<string>;
  tenant_id: string;
}

export interface SecurityTenantConfig {
  branding: Json | null;
  config_version: Generated<number>;
  cost_rate_ownership: string | null;
  deployment_mode: Generated<string>;
  enabled_modules: Json | null;
  flags: Generated<Json>;
  isolation_level: Generated<string>;
  latency_target_seconds: number | null;
  retention_policy: Json | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SecurityUserRole {
  role_id: number;
  tenant_id: Generated<string>;
  user_id: number;
}

export interface TxnAnnCharge {
  base_no: string | null;
  charge_no: string;
  charge_wt_mt: Numeric | null;
  cumm_loading_mt: Numeric | null;
  cumm_unloading_mt: Numeric | null;
  dew_point_h2: Numeric | null;
  dew_point_n2: Numeric | null;
  exp_unloading_time: Timestamp | null;
  furnace_id: number | null;
  grade_code: string | null;
  loading_mt: Numeric | null;
  no_of_coils: number | null;
  oxygen_pct: Numeric | null;
  prod_date: Timestamp | null;
  shift_code: string | null;
  shift_log_id: Int8;
  status: string | null;
  temperature_degc: Numeric | null;
  tenant_id: Generated<string>;
  unloading_mt: Numeric | null;
  unloading_wt_mt: Numeric | null;
}

export interface TxnAnnChargeCoil {
  charge_no: string;
  coil_no: string;
  seq_no: number | null;
  tenant_id: Generated<string>;
}

export interface TxnCrm6Order {
  batch_id: Int8;
  batch_number: string;
  coil_no: string;
  created_at: Generated<Timestamp>;
  customer_name: string;
  grade_code: string;
  input_thk_mm: Numeric | null;
  logged_in_user_id: number | null;
  order_id: Generated<Int8>;
  ppc_thk_mm: Numeric;
  ppc_weight_mt: Numeric;
  prod_date: Timestamp | null;
  prod_duration_min: number | null;
  prod_end_at: Timestamp | null;
  prod_start_at: Timestamp | null;
  production_day: Timestamp | null;
  shift_code: string | null;
  shift_log_id: Int8 | null;
  slit_id: string | null;
  status: Generated<string>;
  sub_process: string;
  updated_at: Generated<Timestamp>;
  width_mm: Numeric;
}

export interface TxnCrm6Rolling {
  actual_weight_mt: Numeric | null;
  associate_rw: string | null;
  destination: string | null;
  destination_override: Generated<boolean | null>;
  dtr: Numeric | null;
  etr: Numeric | null;
  final_thk_mm: Numeric | null;
  order_id: Int8;
  prod_date: Timestamp | null;
  rerolling: Generated<boolean | null>;
  roll_finish: string | null;
  roll_in_code: string | null;
  roll_in_no: string | null;
  roll_out_code: string | null;
  roll_out_no: string | null;
  shift_code: string | null;
  total_passes: number | null;
}

export interface TxnCrm6RollingPass {
  order_id: Int8;
  pass_id: Generated<Int8>;
  pass_no: number;
  thickness_mm: Numeric;
}

export interface TxnCrm6ShiftSummary {
  coolant_press_kgcm2: Numeric | null;
  coolant_temp_degc: Numeric | null;
  scrap_kg: Numeric | null;
  shift_log_id: Int8;
  submitted_at: Timestamp | null;
  submitted_by: number | null;
  summary_id: Generated<Int8>;
  total_prod_mt: Numeric | null;
  total_reroll_mt: Numeric | null;
  total_rolling_mt: Numeric | null;
  total_skinpass_mt: Numeric | null;
}

export interface TxnCrm6Skinpass {
  actual_weight_mt: Numeric | null;
  ann_hard: Numeric | null;
  load_max_t: Numeric | null;
  load_min_t: Numeric | null;
  operating_mode: string | null;
  order_id: Int8;
  output_thk_mm: Numeric | null;
  rw_tension_1: Numeric | null;
  rw_tension_2: Numeric | null;
  stretch_pct: Numeric | null;
}

export interface TxnCrmRollChange {
  change_id: Generated<Int8>;
  changed_at: Generated<Timestamp>;
  new_roll_code: string | null;
  new_roll_no: string;
  operator_id: number | null;
  order_id: Int8;
  prev_roll_code: string | null;
  prev_roll_no: string | null;
  reason_text: string | null;
  roll_position: string;
}

export interface TxnDefectEntry {
  coil_no: string | null;
  defect_code: string;
  defect_id: Generated<Int8>;
  entry_id: Int8;
  location: string | null;
  process_id: number;
  prod_date: Timestamp | null;
  qty_mt: Numeric | null;
  shift_code: string | null;
  tenant_id: Generated<string>;
}

export interface TxnIdempotencyKey {
  created_at: Generated<Timestamp>;
  key: string;
  response_body: Json | null;
  response_status: number;
}

export interface TxnMachineHandover {
  accepted_at: Timestamp | null;
  batch_number: string | null;
  breakdown_code: string | null;
  breakdown_description: string | null;
  clarification_notes: string | null;
  created_at: Generated<Timestamp>;
  created_by_boundary: Generated<boolean>;
  downtime_minutes: number | null;
  handover_id: Generated<string>;
  handover_priority: Generated<string>;
  incoming_operator_id: number | null;
  incoming_prod_date: Timestamp;
  incoming_shift_code: string;
  machine_code: string;
  machine_status: string;
  maintenance_status: string | null;
  open_stoppages: Generated<Json>;
  order_id: Int8 | null;
  outgoing_operator_id: number;
  outgoing_prod_date: Timestamp;
  outgoing_shift_code: string;
  process_code: string;
  production_snapshot: Generated<Json>;
  queue_snapshot: Generated<Json>;
  remarks: string;
  status: Generated<string>;
}

export interface TxnMachineShiftSession {
  closed_at: Timestamp | null;
  machine_code: string;
  operator_user_id: number;
  override_id: Int8 | null;
  prod_date: Timestamp;
  session_id: Generated<Int8>;
  shift_code: string;
  shift_log_id: Int8 | null;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface TxnMachineStateEvent {
  batch_number: string | null;
  category_code: string | null;
  /**
   * Computed when ended_at is set: (ended_at - occurred_at) in minutes.
   */
  duration_min: Numeric | null;
  /**
   * Set when the paired *_ENDED event is recorded. NULL = event is still active.
   */
  ended_at: Timestamp | null;
  event_id: Generated<Int8>;
  /**
   * One of: RUNNING_STARTED, RUNNING_ENDED, STOPPAGE_STARTED, STOPPAGE_ENDED, IDLE_STARTED, IDLE_ENDED, MAINTENANCE_STARTED, MAINTENANCE_ENDED
   */
  event_type: string;
  machine_code: string;
  meta: Json | null;
  occurred_at: Generated<Timestamp>;
  operator_id: number | null;
  order_id: Int8 | null;
  reason: string | null;
  shift_code: string | null;
  tenant_id: Generated<string>;
}

export interface TxnOrderMachineTransfer {
  assigned_by: number | null;
  batch_number: string;
  destination_machine_code: string;
  order_id: Int8 | null;
  reason: string | null;
  source_machine_code: string;
  sub_process: string;
  transfer_id: Generated<Int8>;
  transfer_type: Generated<string>;
  transferred_at: Generated<Timestamp>;
}

export interface TxnOrderRejection {
  created_at: Generated<Timestamp>;
  defect_codes: Json | null;
  operator_id: number;
  order_id: Int8;
  rejection_id: Generated<Int8>;
  rejection_reason: string;
  remarks: string;
  tenant_id: Generated<string>;
}

export interface TxnOrderRemark {
  created_at: Generated<Timestamp>;
  defect_codes: Json | null;
  operator_id: number | null;
  order_id: Int8;
  remark_id: Generated<Int8>;
  text: string;
}

export interface TxnOrderShiftAttribution {
  attribution_id: Generated<Int8>;
  breakdown_minutes: Generated<number>;
  machine_code: string;
  order_id: Int8;
  prod_date: Timestamp;
  production_mt: Generated<Numeric>;
  runtime_minutes: Generated<number>;
  shift_code: string;
  shift_log_id: Int8;
  stoppage_minutes: Generated<number>;
}

export interface TxnProdCrs {
  actual_thk_front_mm: Numeric | null;
  actual_thk_rear_mm: Numeric | null;
  actual_width_mm: Numeric | null;
  camber_waviness: string | null;
  coating_wt_br: Numeric | null;
  coating_wt_matt: Numeric | null;
  coil_no: string;
  coil_width_mm: Numeric | null;
  elongation_pct: Numeric | null;
  entry_id: Generated<Int8>;
  for_ctl_mt: Numeric | null;
  hardness_hrb: Numeric | null;
  hardness_vpn: Numeric | null;
  hold_mt: Numeric | null;
  ib_tiecv: string | null;
  nominal_thk_mm: Numeric | null;
  output_wt_mt: Numeric | null;
  prod_date: Timestamp | null;
  ra_um: Numeric | null;
  rejection_id_mt: Numeric | null;
  rejection_od_mt: Numeric | null;
  remarks: string | null;
  rp_oil_grade: string | null;
  rz_um: Numeric | null;
  shift_code: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  slit_no: string | null;
  tenant_id: Generated<string>;
  uts_nmm2: Numeric | null;
  ysr_burr: string | null;
}

export interface TxnProdCrsSlit {
  child_coil_no: string | null;
  entry_id: Int8;
  slit_id: Generated<Int8>;
  slot: string | null;
  tenant_id: Generated<string>;
  width_mm: Numeric | null;
}

export interface TxnProdCtl {
  actual_length_mm: Numeric | null;
  coil_no: string;
  entry_id: Generated<Int8>;
  estimated_suppressed: string | null;
  hold_mt: Numeric | null;
  low_speed: string | null;
  no_bundles: number | null;
  no_pieces: number | null;
  nominal_set_length_mm: Numeric | null;
  prod_date: Timestamp | null;
  rejection_mt: Numeric | null;
  remarks: string | null;
  shift_code: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  tenant_id: Generated<string>;
  thk_mm: Numeric | null;
  time_from: string | null;
  time_to: string | null;
  total_prod_mt: Numeric | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
}

export interface TxnProdHrs {
  actual_slit_width_from_mm: Numeric | null;
  actual_slit_width_to_mm: Numeric | null;
  actual_width_mm: Numeric | null;
  coil_no: string;
  entry_id: Generated<Int8>;
  nominal_thk_mm: Numeric | null;
  nominal_width_mm: Numeric | null;
  prod_date: Timestamp | null;
  remarks: string | null;
  scrap_mt: Numeric | null;
  scrap_pct: Numeric | null;
  shift_code: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  tenant_id: Generated<string>;
  time_from: string | null;
  time_to: string | null;
  weight_mt: Numeric | null;
}

export interface TxnProdHrsSlit {
  child_coil_no: string | null;
  entry_id: Int8;
  slit_id: Generated<Int8>;
  slot: string;
  taper: string | null;
  tenant_id: Generated<string>;
  thk_mm: Numeric | null;
  width_mm: Numeric | null;
}

export interface TxnProdPkl {
  coil_no: string;
  entry_id: Generated<Int8>;
  heat_no: string | null;
  leader_end: string | null;
  line_speed_mpm: Numeric | null;
  prod_date: Timestamp | null;
  remarks: string | null;
  shift_code: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  source: string | null;
  tenant_id: Generated<string>;
  thk_mm: Numeric | null;
  time_from: string | null;
  time_to: string | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
  wip: string | null;
}

export interface TxnProdPklChart {
  acid_strength_pct: Numeric | null;
  burner_pressure_kgcm2: Numeric | null;
  chart_id: Generated<Int8>;
  chart_time: string;
  dosage_acid: Numeric | null;
  dosage_inhibitor: Numeric | null;
  dosage_water: Numeric | null;
  hot_air_temp_degc: Numeric | null;
  iron_strength_pct: Numeric | null;
  rinse_acid_pct: Numeric | null;
  rinse_cl: Numeric | null;
  rinse_flow: Numeric | null;
  rinse_iron_pct: Numeric | null;
  rinse_ph: Numeric | null;
  rinse_temp_degc: Numeric | null;
  shift_log_id: Int8;
  steam_inlet_kgcm2: Numeric | null;
  steam_outlet_kgcm2: Numeric | null;
  tank_level: Numeric | null;
  tank_no: number | null;
  tank_temp_degc: Numeric | null;
  tenant_id: Generated<string>;
}

export interface TxnProdRwd {
  coil_no: string;
  entry_id: Generated<Int8>;
  output_thk_mm: Numeric | null;
  prod_date: Timestamp | null;
  remarks: string | null;
  rw_tension_1_kg: Numeric | null;
  rw_tension_2_kg: Numeric | null;
  rw_tension_3_kg: Numeric | null;
  shift_code: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  surface_finish: string | null;
  tenant_id: Generated<string>;
  thk_mm: Numeric | null;
  time_from: string | null;
  time_to: string | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
}

export interface TxnSessionCrew {
  created_at: Generated<Timestamp>;
  crew_id: Int8;
  session_crew_id: Generated<Int8>;
  session_id: Int8;
  tenant_id: Generated<string>;
}

export interface TxnShiftEventAudit {
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string | null;
  event_id: Generated<Int8>;
  event_type: string;
  machine_code: string | null;
  payload: Generated<Json>;
  user_id: number | null;
}

export interface TxnShiftLog {
  approved_at: Timestamp | null;
  approver_id: number | null;
  line_incharge_id: number | null;
  mill_type: string | null;
  process_id: number;
  prod_date: Timestamp;
  /**
   * The active ruleset version at the time of submission
   */
  ruleset_version: number | null;
  shift_code: string;
  shift_log_id: Generated<Int8>;
  shift_manager_id: number | null;
  state: Generated<string>;
  submitted_at: Timestamp | null;
  target_mt: Numeric | null;
  tenant_id: Generated<string>;
  total_prod_mt: Numeric | null;
}

export interface TxnShiftOverrideAudit {
  created_at: Generated<Timestamp>;
  machine_code: string | null;
  override_id: Generated<Int8>;
  prod_date: Timestamp;
  reason_code: string;
  reason_detail: string | null;
  selected_shift_code: string;
  user_id: number;
}

export interface TxnStoppage {
  breakdown_code: string | null;
  category_code: string;
  duration_min: number | null;
  end_at: Timestamp | null;
  machine_code: string | null;
  operator_id: number | null;
  order_id: Int8 | null;
  prod_date: Timestamp | null;
  remarks: string | null;
  shift_code: string | null;
  shift_log_id: Int8 | null;
  start_at: Generated<Timestamp>;
  stoppage_id: Generated<Int8>;
  tenant_id: Generated<string>;
}

export interface TxnValidationOverrides {
  created_at: Generated<Timestamp>;
  field_path: string;
  override_by: number;
  override_id: Generated<Int8>;
  reason: string;
  shift_log_id: Int8;
}

export interface DB {
  "archive.prod_crm": ArchiveProdCrm;
  "archive.prod_skp": ArchiveProdSkp;
  "archive.prod_skp_pass": ArchiveProdSkpPass;
  "audit.audit_log": AuditAuditLog;
  "audit.dpr_month_lock": AuditDprMonthLock;
  "audit.export_job": AuditExportJob;
  "audit.lineage_ref": AuditLineageRef;
  "canon.equipment_node": CanonEquipmentNode;
  "canon.event": CanonEvent;
  "canon.production_count": CanonProductionCount;
  "coil.coil": CoilCoil;
  "config.ruleset_version": ConfigRulesetVersion;
  "config.validation_rule": ConfigValidationRule;
  "dpr.daily_entry": DprDailyEntry;
  "dpr.field_mapping": DprFieldMapping;
  "dpr.month": DprMonth;
  "dpr.source_map": DprSourceMap;
  "dpr.template": DprTemplate;
  "master.crm_sub_process": MasterCrmSubProcess;
  "master.customer": MasterCustomer;
  "master.defect_code": MasterDefectCode;
  "master.furnace": MasterFurnace;
  "master.grade": MasterGrade;
  "master.grade_spec": MasterGradeSpec;
  "master.line_area": MasterLineArea;
  "master.machine": MasterMachine;
  "master.machine_crew_roster": MasterMachineCrewRoster;
  "master.operator": MasterOperator;
  "master.process": MasterProcess;
  "master.route_code": MasterRouteCode;
  "master.rp_oil_grade": MasterRpOilGrade;
  "master.shift": MasterShift;
  "master.stoppage_category": MasterStoppageCategory;
  "master.stoppage_code": MasterStoppageCode;
  "master.surface_finish": MasterSurfaceFinish;
  pgmigrations: Pgmigrations;
  pgmigrations_m1: PgmigrationsM1;
  "planning.coil_plan": PlanningCoilPlan;
  "planning.import_batch": PlanningImportBatch;
  "planning.order_journey": PlanningOrderJourney;
  "planning.order_journey_step": PlanningOrderJourneyStep;
  "planning.plan_order": PlanningPlanOrder;
  "planning.ppc_batch": PlanningPpcBatch;
  "planning.ppc_rolling_pass_plan": PlanningPpcRollingPassPlan;
  "planning.production_target": PlanningProductionTarget;
  "planning.queue_handoff": PlanningQueueHandoff;
  "security.app_user": SecurityAppUser;
  "security.device_registration": SecurityDeviceRegistration;
  "security.line_access": SecurityLineAccess;
  "security.machine_access": SecurityMachineAccess;
  "security.permission": SecurityPermission;
  "security.role": SecurityRole;
  "security.tenant": SecurityTenant;
  "security.tenant_config": SecurityTenantConfig;
  "security.user_role": SecurityUserRole;
  "txn.ann_charge": TxnAnnCharge;
  "txn.ann_charge_coil": TxnAnnChargeCoil;
  "txn.crm_roll_change": TxnCrmRollChange;
  "txn.crm6_order": TxnCrm6Order;
  "txn.crm6_rolling": TxnCrm6Rolling;
  "txn.crm6_rolling_pass": TxnCrm6RollingPass;
  "txn.crm6_shift_summary": TxnCrm6ShiftSummary;
  "txn.crm6_skinpass": TxnCrm6Skinpass;
  "txn.defect_entry": TxnDefectEntry;
  "txn.idempotency_key": TxnIdempotencyKey;
  "txn.machine_handover": TxnMachineHandover;
  "txn.machine_shift_session": TxnMachineShiftSession;
  "txn.machine_state_event": TxnMachineStateEvent;
  "txn.order_machine_transfer": TxnOrderMachineTransfer;
  "txn.order_rejection": TxnOrderRejection;
  "txn.order_remark": TxnOrderRemark;
  "txn.order_shift_attribution": TxnOrderShiftAttribution;
  "txn.prod_crs": TxnProdCrs;
  "txn.prod_crs_slit": TxnProdCrsSlit;
  "txn.prod_ctl": TxnProdCtl;
  "txn.prod_hrs": TxnProdHrs;
  "txn.prod_hrs_slit": TxnProdHrsSlit;
  "txn.prod_pkl": TxnProdPkl;
  "txn.prod_pkl_chart": TxnProdPklChart;
  "txn.prod_rwd": TxnProdRwd;
  "txn.session_crew": TxnSessionCrew;
  "txn.shift_event_audit": TxnShiftEventAudit;
  "txn.shift_log": TxnShiftLog;
  "txn.shift_override_audit": TxnShiftOverrideAudit;
  "txn.stoppage": TxnStoppage;
  "txn.validation_overrides": TxnValidationOverrides;
}
