/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditAuditLog {
  action: string;
  audit_id: Generated<Int8>;
  change_request_id: Int8 | null;
  column_name: string | null;
  new_value: string | null;
  old_value: string | null;
  record_pk: string;
  table_name: string;
  ts: Generated<Timestamp>;
  user_id: number | null;
}

export interface AuditChangeRequest {
  approved_by: number | null;
  cr_id: Generated<Int8>;
  decided_at: Timestamp | null;
  reason: string;
  record_pk: string;
  rejection_note: string | null;
  requested_at: Generated<Timestamp>;
  requested_by: number;
  state: Generated<string>;
  table_name: string;
  proposed_changes: Json | null;
}

export interface AuditExportJob {
  artifact_bytes: Int8 | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  data_version: string | null;
  error_message: string | null;
  export_id: Generated<Int8>;
  export_type: Generated<string>;
  file_path: string | null;
  format: string;
  job_status: Generated<string>;
  params_json: Json | null;
  progress: Generated<number>;
  requested_by: number | null;
  row_count: number | null;
  scope: string;
  sha256: string | null;
  storage_uri: string | null;
}

export interface ConfigRulesetVersion {
  id: Generated<number>;
  published_at: Generated<Timestamp | null>;
  published_by: string | null;
  version: Generated<number>;
}

export interface ConfigValidationRule {
  field_id: string;
  is_active: Generated<boolean>;
  params: Json;
  rule_type: string;
  severity: string;
  updated_at: Generated<Timestamp | null>;
  updated_by: string | null;
}

export interface CoilCoil {
  coil_no: string;
  coil_thk_mm: Numeric | null;
  coil_width_mm: Numeric | null;
  created_at: Generated<Timestamp>;
  current_process_id: number | null;
  customer_id: number | null;
  grade_code: string | null;
  heat_no: string | null;
  next_dest: string | null;
  nominal_width_mm: Numeric | null;
  parent_coil_no: string | null;
  status: Generated<string>;
  surface_finish: string | null;
  weight_mt: Numeric | null;
}

export interface CoilCoilProcessHistory {
  coil_no: string;
  completed_at: Timestamp | null;
  entered_at: Generated<Timestamp>;
  in_thk_mm: Numeric | null;
  out_thk_mm: Numeric | null;
  out_weight_mt: Numeric | null;
  process_id: number;
}

export interface MasterCustomer {
  customer_code: string;
  customer_id: Generated<number>;
  customer_name: string;
  is_active: Generated<boolean>;
}

export interface MasterDefectCode {
  applies_to: string | null;
  defect_code: string;
  description: string;
  is_active: Generated<boolean>;
  symbol: string | null;
}

export interface MasterFurnace {
  code: string;
  furnace_id: number;
  furnace_type: Generated<string | null>;
  name: string | null;
}

export interface MasterGrade {
  grade_code: string;
  description: string | null;
  grade_family: string | null;
  pkl_speed_min: string | null;
  pkl_speed_max: string | null;
  acid_pct_min: string | null;
  acid_pct_max: string | null;
  is_active: Generated<boolean>;
}

export interface MasterGradeSpec {
  customer_id: number | null;
  elongation_pct_min: Numeric | null;
  grade_code: string;
  hardness_hrb_max: Numeric | null;
  hardness_hrb_min: Numeric | null;
  ra_um_max: Numeric | null;
  spec_id: Generated<number>;
  uts_nmm2_max: Numeric | null;
  uts_nmm2_min: Numeric | null;
}

export interface MasterOperator {
  emp_code: string;
  full_name: string;
  is_active: Generated<boolean>;
  operator_id: Generated<number>;
}

export interface MasterProcess {
  code: string;
  has_mill_type: Generated<boolean>;
  name: string;
  process_id: number;
  seq_no: number;
}

export interface MasterRpOilGrade {
  description: string | null;
  rp_oil_grade: string;
}

export interface MasterShift {
  end_time: string;
  name: string;
  shift_code: string;
  start_time: string;
}

export interface MasterLineArea {
  area_code: string;
  dpr_area_label: string;
  is_dpr_reported: Generated<boolean>;
  name: string;
  operating_minutes_base: number;
  process_code: string | null;
  sort_order: number;
}

export interface MasterStoppageCode {
  agency_code: string | null;
  category: string;
  description: string;
  dpr_category: string | null;
  is_active: Generated<boolean>;
  is_planned: Generated<boolean>;
  stoppage_code: string;
}

export interface MasterSurfaceFinish {
  description: string | null;
  surface_finish: string;
}

export interface PlanningCoilPlan {
  coil_no: string | null;
  coil_plan_id: Generated<Int8>;
  plan_order_id: Int8 | null;
  planned_date: Timestamp | null;
  planned_process_id: number | null;
  seq_no: number | null;
}

export interface PlanningImportBatch {
  error_count: Generated<number | null>;
  errors_json: Json | null;
  file_name: string | null;
  import_batch_id: Generated<Int8>;
  imported_at: Generated<Timestamp>;
  imported_by: number | null;
  row_count: number | null;
  source: string;
  status: Generated<string>;
}

export interface MasterCrmSubProcess {
  machine_code: string;
  name: string;
  sub_process_code: string;
}

export interface MasterMachine {
  machine_code: string;
  name: string;
  process_id: number | null;
  process_code: string | null;
  machine_status: Generated<string>;
}

export interface MasterStoppageCategory {
  agency_code: string | null;
  category_code: string;
  dpr_category: string | null;
  label: string;
  requires_breakdown_code: Generated<boolean>;
}

export interface PlanningProductionTarget {
  area_code: string;
  created_at: Generated<Timestamp>;
  period: Timestamp;
  target_id: Generated<Int8>;
  target_mt: Numeric | null;
  target_rate: Numeric | null;
}

export interface PlanningPpcBatch {
  batch_id: Generated<Int8>;
  batch_number: string;
  coil_no: string;
  customer_name: string;
  destination: string | null;
  grade_code: string;
  import_batch_id: Int8 | null;
  imported_at: Generated<Timestamp>;
  input_thk_mm: Numeric;
  machine_code: string;
  machine_allocated: Generated<boolean>;
  plan_date: Timestamp;
  ppc_reroll_flag: Generated<boolean | null>;
  ppc_thk_mm: Numeric;
  ppc_weight_mt: Numeric;
  queue_seq: number | null;
  raw_row_json: Json | null;
  roll_finish: string | null;
  sap_order_no: string | null;
  shift_code: string;
  slit_id: string | null;
  sub_process: string;
  width_mm: Numeric;
  process_route_raw: string | null;
  finish_thk_mm?: Numeric | null;
  active_rolling_pass_no?: Generated<number | null>;
  item_no?: string | null;
  from_work_center?: string | null;
  to_work_center?: string | null;
  ppc_remarks?: string | null;
  import_remark?: string | null;
  min_thk_tol_mm?: Numeric | null;
  max_thk_tol_mm?: Numeric | null;
  process_route_canonical?: string | null;
  coil_count?: Generated<number | null>;
}

export interface PlanningPpcRollingPassPlan {
  plan_id: Generated<Int8>;
  batch_id: Int8;
  pass_no: number;
  target_thk_mm: Numeric | null;
  roll_finish: string | null;
  is_required: boolean;
}

export interface PlanningOrderJourney {
  journey_id: Generated<Int8>;
  coil_no: string;
  route_raw: string;
  current_step_no: number;
  status: string;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface PlanningOrderJourneyStep {
  step_id: Generated<Int8>;
  journey_id: Int8;
  step_no: number;
  route_code: string;
  display_label: string;
  process_code: string | null;
  machine_code: string | null;
  sub_process: string | null;
  status: string;
  started_at: Timestamp | null;
  completed_at: Timestamp | null;
  queue_batch_id: Int8 | null;
}

export interface PlanningQueueHandoff {
  handoff_id: Generated<Int8>;
  journey_id: Int8;
  source_step_id: Int8;
  target_step_no: number;
  target_batch_id: Int8 | null;
  source: string;
  created_at: Generated<Timestamp>;
}

export interface SecurityMachineAccess {
  user_id: number;
  machine_code: string;
  access_level: string;
  assigned_by: number | null;
  assigned_at: Generated<Timestamp>;
}

export interface PlanningPlanOrder {
  customer_id: number | null;
  due_date: Timestamp | null;
  grade_code: string | null;
  import_batch_id: Int8 | null;
  plan_order_id: Generated<Int8>;
  planned_qty_mt: Numeric | null;
  sap_order_no: string | null;
  surface_finish: string | null;
  target_thk_mm: Numeric | null;
  target_width_mm: Numeric | null;
}

export interface SecurityAppUser {
  auth_subject: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  emp_code: string | null;
  full_name: string;
  pin_failed_attempts: Generated<number>;
  pin_hash: string | null;
  pin_locked_until: Timestamp | null;
  status: Generated<string>;
  user_id: Generated<number>;
  username: string;
}

export interface SecurityLineAccess {
  access_level: Generated<string>;
  process_id: number;
  user_id: number;
}

export interface SecurityDeviceRegistration {
  device_id: string;
  process_code: string;
  registered_at: Generated<Timestamp>;
  last_heartbeat: Timestamp | null;
  tenant_id: Generated<string>;
}

export interface SecurityRole {
  description: string | null;
  role_id: number;
  role_name: string;
}

export interface SecurityTenantConfig {
  branding: Json | null;
  config_version: Generated<number>;
  cost_rate_ownership: string | null;
  deployment_mode: Generated<string>;
  enabled_modules: Json | null;
  isolation_level: Generated<string>;
  latency_target_seconds: number | null;
  retention_policy: Json | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SecurityUserRole {
  role_id: number;
  user_id: number;
}

export interface TxnAnnCharge {
  base_no: string | null;
  charge_no: string;
  charge_wt_mt: Numeric | null;
  cumm_loading_mt: Numeric | null;
  cumm_unloading_mt: Numeric | null;
  dew_point_h2: Numeric | null;
  dew_point_n2: Numeric | null;
  exp_unloading_time: Timestamp | null;
  furnace_id: number | null;
  grade_code: string | null;
  loading_mt: Numeric | null;
  no_of_coils: number | null;
  shift_log_id: Int8;
  status: string | null;
  temperature_degc: Numeric | null;
  unloading_mt: Numeric | null;
  unloading_wt_mt: Numeric | null;
  oxygen_pct: Numeric | null;
}

export interface TxnAnnChargeCoil {
  charge_no: string;
  coil_no: string;
  seq_no: number | null;
}

export interface TxnSixHiOrder {
  batch_id: Int8;
  batch_number: string;
  coil_no: string;
  created_at: Generated<Timestamp>;
  customer_name: string;
  grade_code: string;
  input_thk_mm: Numeric;
  logged_in_user_id: number | null;
  order_id: Generated<Int8>;
  ppc_thk_mm: Numeric;
  ppc_weight_mt: Numeric;
  prod_duration_min: number | null;
  prod_end_at: Timestamp | null;
  prod_start_at: Timestamp | null;
  production_day: Timestamp | null;
  shift_log_id: Int8 | null;
  slit_id: string | null;
  status: Generated<string>;
  sub_process: string;
  updated_at: Generated<Timestamp>;
  width_mm: Numeric;
}

export interface TxnSixHiRolling {
  actual_weight_mt: Numeric | null;
  associate_rw: string | null;
  destination: string | null;
  destination_override: Generated<boolean | null>;
  dtr: Numeric | null;
  etr: Numeric | null;
  final_thk_mm: Numeric | null;
  order_id: Int8;
  rerolling: Generated<boolean | null>;
  roll_finish: string | null;
  roll_in_code: string | null;
  roll_in_no: string | null;
  roll_out_code: string | null;
  roll_out_no: string | null;
  total_passes: number | null;
}

export interface TxnSixHiRollingPass {
  order_id: Int8;
  pass_id: Generated<Int8>;
  pass_no: number;
  thickness_mm: Numeric;
}

export interface TxnSixHiShiftSummary {
  coolant_press_kgcm2: Numeric | null;
  coolant_temp_degc: Numeric | null;
  scrap_kg: Numeric | null;
  shift_log_id: Int8;
  submitted_at: Timestamp | null;
  submitted_by: number | null;
  summary_id: Generated<Int8>;
  total_prod_mt: Numeric | null;
  total_reroll_mt: Numeric | null;
  total_rolling_mt: Numeric | null;
  total_skinpass_mt: Numeric | null;
}

export interface TxnSixHiSkinpass {
  actual_weight_mt: Numeric | null;
  ann_hard: Numeric | null;
  load_max_t: Numeric | null;
  load_min_t: Numeric | null;
  operating_mode: string | null;
  order_id: Int8;
  output_thk_mm: Numeric | null;
  rw_tension_1: Numeric | null;
  rw_tension_2: Numeric | null;
  stretch_pct: Numeric | null;
}

export interface TxnCrmRollChange {
  change_id: Generated<Int8>;
  changed_at: Generated<Timestamp>;
  new_roll_code: string | null;
  new_roll_no: string;
  operator_id: number | null;
  order_id: Int8;
  prev_roll_code: string | null;
  prev_roll_no: string | null;
  reason_text: string | null;
  roll_position: string;
}

export interface TxnOrderRejection {
  created_at: Generated<Timestamp>;
  defect_codes: JsonValue | null;
  operator_id: number;
  order_id: Int8;
  rejection_id: Generated<Int8>;
  rejection_reason: string;
  remarks: string;
}

export interface TxnOrderRemark {
  created_at: Generated<Timestamp>;
  defect_codes: JsonValue | null;
  operator_id: number | null;
  order_id: Int8;
  remark_id: Generated<Int8>;
  text: string;
}

export interface TxnOrderStoppage {
  breakdown_code: string | null;
  category_code: string;
  duration_min: number | null;
  end_at: Timestamp | null;
  operator_id: number | null;
  order_id: Int8;
  remarks: string | null;
  start_at: Generated<Timestamp>;
  stoppage_id: Generated<Int8>;
}

export interface TxnCrewEntry {
  crew_id: Generated<Int8>;
  operator_id: number;
  role_code: string;
  shift_log_id: Int8;
}

export interface TxnDefectEntry {
  coil_no: string | null;
  defect_code: string;
  defect_id: Generated<Int8>;
  entry_id: Int8;
  location: string | null;
  process_id: number;
  qty_mt: Numeric | null;
}

export interface TxnProdCrm {
  ann_hardness: Numeric | null;
  coil_no: string;
  elongation_pct: Numeric | null;
  entry_id: Generated<Int8>;
  hardness_hrb: Numeric | null;
  hardness_vpn: Numeric | null;
  input_thk_mm: Numeric | null;
  loss_pct: Numeric | null;
  oil_consumption: Numeric | null;
  oil_level_final: Numeric | null;
  oil_level_initial: Numeric | null;
  output_thk_mm: Numeric | null;
  remarks: string | null;
  roll_in: string | null;
  roll_out: string | null;
  rw_tension_kg: Numeric | null;
  scrap_mt: Numeric | null;
  shift_log_id: Int8;
  sl_no: number | null;
  stretch_pct: Numeric | null;
  time_from: string | null;
  time_to: string | null;
  tkg_weight_mt: Numeric | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
}

export interface TxnProdCrs {
  actual_thk_front_mm: Numeric | null;
  actual_thk_rear_mm: Numeric | null;
  actual_width_mm: Numeric | null;
  camber_waviness: string | null;
  coating_wt_br: Numeric | null;
  coating_wt_matt: Numeric | null;
  coil_no: string;
  coil_width_mm: Numeric | null;
  elongation_pct: Numeric | null;
  entry_id: Generated<Int8>;
  for_ctl_mt: Numeric | null;
  hardness_hrb: Numeric | null;
  hardness_vpn: Numeric | null;
  hold_mt: Numeric | null;
  ib_tiecv: string | null;
  nominal_thk_mm: Numeric | null;
  output_wt_mt: Numeric | null;
  ra_um: Numeric | null;
  rejection_id_mt: Numeric | null;
  rejection_od_mt: Numeric | null;
  remarks: string | null;
  rp_oil_grade: string | null;
  rz_um: Numeric | null;
  shift_log_id: Int8;
  sl_no: number | null;
  slit_no: string | null;
  uts_nmm2: Numeric | null;
  ysr_burr: string | null;
}

export interface TxnProdCrsSlit {
  child_coil_no: string | null;
  entry_id: Int8;
  slit_id: Generated<Int8>;
  slot: string | null;
  width_mm: Numeric | null;
}

export interface TxnProdCtl {
  actual_length_mm: Numeric | null;
  coil_no: string;
  entry_id: Generated<Int8>;
  estimated_suppressed: string | null;
  hold_mt: Numeric | null;
  low_speed: string | null;
  no_bundles: number | null;
  no_pieces: number | null;
  nominal_set_length_mm: Numeric | null;
  rejection_mt: Numeric | null;
  remarks: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  thk_mm: Numeric | null;
  time_from: string | null;
  time_to: string | null;
  total_prod_mt: Numeric | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
}

export interface TxnProdGlv {
  entry_id: Generated<Int8>;
  shift_log_id: Int8;
  sl_no: number;
  coil_no: string;
  zinc_coating_gsm: Numeric | null;
  spangle_type: string | null;
  weight_mt: Numeric;
  remarks: string | null;
  time_from: Timestamp | null;
  time_to: Timestamp | null;
  created_at: Generated<Timestamp>;
}

export interface TxnProdHrs {
  actual_slit_width_from_mm: Numeric | null;
  actual_slit_width_to_mm: Numeric | null;
  actual_width_mm: Numeric | null;
  coil_no: string;
  entry_id: Generated<Int8>;
  nominal_thk_mm: Numeric | null;
  nominal_width_mm: Numeric | null;
  remarks: string | null;
  scrap_mt: Numeric | null;
  scrap_pct: Numeric | null;
  shift_log_id: Int8;
  sl_no: number | null;
  time_from: string | null;
  time_to: string | null;
  weight_mt: Numeric | null;
}

export interface TxnProdHrsSlit {
  child_coil_no: string | null;
  entry_id: Int8;
  slit_id: Generated<Int8>;
  slot: string;
  taper: string | null;
  thk_mm: Numeric | null;
  width_mm: Numeric | null;
}

export interface TxnProdPkl {
  coil_no: string;
  entry_id: Generated<Int8>;
  heat_no: string | null;
  leader_end: string | null;
  line_speed_mpm: Numeric | null;
  remarks: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  source: string | null;
  thk_mm: Numeric | null;
  time_from: string | null;
  time_to: string | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
  wip: string | null;
}

export interface TxnProdPklChart {
  acid_strength_pct: Numeric | null;
  burner_pressure_kgcm2: Numeric | null;
  chart_id: Generated<Int8>;
  chart_time: string;
  dosage_acid: Numeric | null;
  dosage_inhibitor: Numeric | null;
  dosage_water: Numeric | null;
  hot_air_temp_degc: Numeric | null;
  iron_strength_pct: Numeric | null;
  rinse_acid_pct: Numeric | null;
  rinse_cl: Numeric | null;
  rinse_flow: Numeric | null;
  rinse_iron_pct: Numeric | null;
  rinse_ph: Numeric | null;
  rinse_temp_degc: Numeric | null;
  shift_log_id: Int8;
  steam_inlet_kgcm2: Numeric | null;
  steam_outlet_kgcm2: Numeric | null;
  tank_level: Numeric | null;
  tank_no: number | null;
  tank_temp_degc: Numeric | null;
}

export interface TxnProdRwd {
  coil_no: string;
  entry_id: Generated<Int8>;
  output_thk_mm: Numeric | null;
  remarks: string | null;
  rw_tension_1_kg: Numeric | null;
  rw_tension_2_kg: Numeric | null;
  rw_tension_3_kg: Numeric | null;
  shift_log_id: Int8;
  sl_no: number | null;
  surface_finish: string | null;
  thk_mm: Numeric | null;
  time_from: string | null;
  time_to: string | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
}

export interface TxnProdSkp {
  coil_no: string;
  coolant_press_kgcm2: Numeric | null;
  coolant_temp_degc: Numeric | null;
  entry_id: Generated<Int8>;
  final_thk_mm: Numeric | null;
  hold_mt: Numeric | null;
  re_rolling: Generated<boolean | null>;
  rejection_mt: Numeric | null;
  remarks: string | null;
  rolls_in: string | null;
  rolls_out: string | null;
  rw_tension_kg: Numeric | null;
  shift_log_id: Int8;
  sl_no: number | null;
  surface_finish: string | null;
  thk_mm: Numeric | null;
  total_passes: number | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
  wt_reroll_mt: Numeric | null;
  wt_rolling_mt: Numeric | null;
  wt_scrap_mt: Numeric | null;
  wt_skinpass_mt: Numeric | null;
}

export interface TxnProdSkpPass {
  entry_id: Int8;
  pass_id: Generated<Int8>;
  pass_no: number;
  thickness_mm: Numeric | null;
}

export interface TxnShiftLog {
  approved_at: Timestamp | null;
  approver_id: number | null;
  handover_at: Timestamp | null;
  handover_incoming_user_id: number | null;
  handover_notes: string | null;
  handover_outgoing_user_id: number | null;
  line_incharge_id: number | null;
  mill_type: string | null;
  prev_shift_log_id: Int8 | null;
  process_id: number;
  prod_date: Timestamp;
  ruleset_version: number | null;
  shift_code: string;
  shift_log_id: Generated<Int8>;
  shift_manager_id: number | null;
  state: Generated<string>;
  submitted_at: Timestamp | null;
  target_mt: Numeric | null;
  total_prod_mt: Numeric | null;
  reject_reason: string | null;
}

export interface TxnStoppageEntry {
  duration_min: number | null;
  remarks: string | null;
  shift_log_id: Int8;
  stoppage_code: string;
  stoppage_id: Generated<Int8>;
  time_from: string;
  time_to: string;
}

export interface TxnValidationOverrides {
  override_id: Generated<Int8>;
  shift_log_id: Int8;
  field_path: string;
  reason: string;
  override_by: number;
  created_at: Generated<Timestamp>;
}

export interface TxnShiftOverrideAudit {
  override_id: Generated<Int8>;
  user_id: number;
  machine_code: string | null;
  selected_shift_code: string;
  prod_date: Timestamp;
  reason_code: string;
  reason_detail: string | null;
  created_at: Generated<Timestamp>;
}

export interface TxnMachineShiftSession {
  session_id: Generated<Int8>;
  machine_code: string;
  shift_code: string;
  prod_date: Timestamp;
  operator_user_id: number;
  shift_log_id: Int8 | null;
  status: string;
  started_at: Generated<Timestamp>;
  closed_at: Timestamp | null;
  override_id: Int8 | null;
}

export interface TxnMachineHandover {
  handover_id: Generated<string>;
  handover_priority: Generated<string>;
  machine_code: string;
  process_code: string;
  order_id: Int8 | null;
  batch_number: string | null;
  outgoing_shift_code: string;
  incoming_shift_code: string;
  outgoing_prod_date: Timestamp;
  incoming_prod_date: Timestamp;
  outgoing_operator_id: number;
  incoming_operator_id: number | null;
  machine_status: string;
  breakdown_code: string | null;
  breakdown_description: string | null;
  downtime_minutes: number | null;
  maintenance_status: string | null;
  remarks: string;
  queue_snapshot: unknown;
  production_snapshot: unknown;
  open_stoppages: unknown;
  status: Generated<string>;
  handover_priority: Generated<string>;
  clarification_notes: string | null;
  created_at: Generated<Timestamp>;
  accepted_at: Timestamp | null;
  created_by_boundary: boolean;
}

export interface TxnOrderShiftAttribution {
  attribution_id: Generated<Int8>;
  order_id: Int8;
  shift_log_id: Int8;
  machine_code: string;
  shift_code: string;
  prod_date: Timestamp;
  runtime_minutes: number;
  production_mt: Numeric;
  stoppage_minutes: number;
  breakdown_minutes: number;
}

export interface TxnShiftEventAudit {
  event_id: Generated<Int8>;
  event_type: string;
  entity_type: string | null;
  entity_id: string | null;
  machine_code: string | null;
  payload: unknown;
  user_id: number | null;
  created_at: Generated<Timestamp>;
}

export interface TxnMachineStateEvent {
  event_id: Generated<Int8>;
  machine_code: string;
  event_type: string;
  occurred_at: Generated<Timestamp>;
  ended_at: Timestamp | null;
  duration_min: Numeric | null;
  order_id: Int8 | null;
  batch_number: string | null;
  operator_id: number | null;
  shift_code: string | null;
  reason: string | null;
  category_code: string | null;
  meta: unknown | null;
  tenant_id: Generated<string>;
}

export interface DB {
  "audit.audit_log": AuditAuditLog;
  "audit.change_request": AuditChangeRequest;
  "audit.export_job": AuditExportJob;
  "config.ruleset_version": ConfigRulesetVersion;
  "config.validation_rule": ConfigValidationRule;
  "coil.coil": CoilCoil;
  "coil.coil_process_history": CoilCoilProcessHistory;
  "master.crm_sub_process": MasterCrmSubProcess;
  "master.customer": MasterCustomer;
  "master.machine": MasterMachine;
  "master.stoppage_category": MasterStoppageCategory;
  "master.defect_code": MasterDefectCode;
  "master.furnace": MasterFurnace;
  "master.grade": MasterGrade;
  "master.grade_spec": MasterGradeSpec;
  "master.line_area": MasterLineArea;
  "master.operator": MasterOperator;
  "master.process": MasterProcess;
  "master.rp_oil_grade": MasterRpOilGrade;
  "master.shift": MasterShift;
  "master.stoppage_code": MasterStoppageCode;
  "master.surface_finish": MasterSurfaceFinish;
  "planning.coil_plan": PlanningCoilPlan;
  "planning.ppc_batch": PlanningPpcBatch;
  "planning.ppc_rolling_pass_plan": PlanningPpcRollingPassPlan;
  "planning.order_journey": PlanningOrderJourney;
  "planning.order_journey_step": PlanningOrderJourneyStep;
  "planning.queue_handoff": PlanningQueueHandoff;
  "planning.import_batch": PlanningImportBatch;
  "planning.plan_order": PlanningPlanOrder;
  "planning.production_target": PlanningProductionTarget;
  "security.app_user": SecurityAppUser;
  "security.device_registration": SecurityDeviceRegistration;
  "security.line_access": SecurityLineAccess;
  "security.tenant_config": SecurityTenantConfig;
  "security.machine_access": SecurityMachineAccess;
  "security.role": SecurityRole;
  "security.user_role": SecurityUserRole;
  "txn.ann_charge": TxnAnnCharge;
  "txn.ann_charge_coil": TxnAnnChargeCoil;
  "txn.crm6_order": TxnSixHiOrder;
  "txn.crm6_rolling": TxnSixHiRolling;
  "txn.crm6_rolling_pass": TxnSixHiRollingPass;
  "txn.crm6_shift_summary": TxnSixHiShiftSummary;
  "txn.crm6_skinpass": TxnSixHiSkinpass;
  "txn.crm_roll_change": TxnCrmRollChange;
  "txn.crew_entry": TxnCrewEntry;
  "txn.order_remark": TxnOrderRemark;
  "txn.order_rejection": TxnOrderRejection;
  "txn.order_stoppage": TxnOrderStoppage;
  "txn.defect_entry": TxnDefectEntry;
  "txn.prod_crm": TxnProdCrm;
  "txn.prod_crs": TxnProdCrs;
  "txn.prod_crs_slit": TxnProdCrsSlit;
  "txn.prod_ctl": TxnProdCtl;
  "txn.prod_glv": TxnProdGlv;
  "txn.prod_hrs": TxnProdHrs;
  "txn.prod_hrs_slit": TxnProdHrsSlit;
  "txn.prod_pkl": TxnProdPkl;
  "txn.prod_pkl_chart": TxnProdPklChart;
  "txn.prod_rwd": TxnProdRwd;
  "txn.prod_skp": TxnProdSkp;
  "txn.prod_skp_pass": TxnProdSkpPass;
  "txn.skp_pass": TxnProdSkpPass;
  "txn.shift_log": TxnShiftLog;
  "txn.stoppage_entry": TxnStoppageEntry;
  "txn.validation_overrides": TxnValidationOverrides;
  "txn.shift_override_audit": TxnShiftOverrideAudit;
  "txn.machine_shift_session": TxnMachineShiftSession;
  "txn.machine_handover": TxnMachineHandover;
  "txn.order_shift_attribution": TxnOrderShiftAttribution;
  "txn.shift_event_audit": TxnShiftEventAudit;
  "txn.machine_state_event": TxnMachineStateEvent;
}
