/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AllAuthRecipeUsers {
  app_id: Generated<string>;
  is_linked_or_is_a_primary_user: Generated<boolean>;
  primary_or_recipe_user_id: string;
  primary_or_recipe_user_time_joined: Int8;
  recipe_id: string;
  tenant_id: Generated<string>;
  time_joined: Int8;
  user_id: string;
}

export interface AppIdToUserId {
  app_id: Generated<string>;
  is_linked_or_is_a_primary_user: Generated<boolean>;
  primary_or_recipe_user_id: string;
  recipe_id: string;
  user_id: string;
}

export interface Apps {
  app_id: Generated<string>;
  created_at_time: Int8 | null;
}

export interface AuditAuditLog {
  action: string;
  audit_id: Generated<Int8>;
  column_name: string | null;
  new_value: string | null;
  old_value: string | null;
  record_pk: string;
  table_name: string;
  tenant_id: Generated<string>;
  ts: Generated<Timestamp>;
  user_id: number | null;
}

export interface AuditDprMonthLock {
  export_job_id: Int8 | null;
  finalized_at: Generated<Timestamp>;
  finalized_by: number | null;
  month: string;
}

export interface AuditExportJob {
  artifact_bytes: Int8 | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  data_version: string | null;
  error_message: string | null;
  export_id: Generated<Int8>;
  export_type: Generated<string>;
  file_path: string | null;
  format: string;
  generated_at: Timestamp | null;
  job_status: Generated<string>;
  params_json: Json | null;
  progress: Generated<number>;
  requested_by: number | null;
  row_count: number | null;
  scope: string;
  sha256: string | null;
  source_record_count: Int8 | null;
  storage_uri: string | null;
  tenant_id: Generated<string>;
}

export interface AuditLineageRef {
  batch_id: string | null;
  created_at: Generated<Timestamp>;
  mapping_version: string | null;
  record_id: string;
  source_row_ref: string | null;
  tenant_id: string;
}

export interface BulkImportUsers {
  app_id: Generated<string>;
  created_at: Int8;
  error_msg: string | null;
  id: string;
  primary_user_id: string | null;
  raw_data: string;
  status: Generated<string | null>;
  updated_at: Int8;
}

export interface CanonEquipmentNode {
  asset_code: string;
  asset_id: Generated<string>;
  created_at: Generated<Timestamp>;
  name: string;
  process_code: string | null;
  tenant_id: string;
}

export interface CanonEvent {
  asset_id: string | null;
  category: string | null;
  created_at: Generated<Timestamp>;
  duration_min: number | null;
  ended_at: Timestamp | null;
  event_id: Generated<string>;
  event_type: string;
  lineage_ref: string;
  payload: Generated<Json>;
  started_at: Timestamp;
  tenant_id: string;
}

export interface CanonProductionCount {
  asset_id: string | null;
  count_id: Generated<string>;
  counted_at: Timestamp;
  created_at: Generated<Timestamp>;
  is_scrap: Generated<boolean>;
  lineage_ref: string;
  quantity: Numeric;
  shift_log_id: Int8 | null;
  tenant_id: string;
  uom: Generated<string>;
}

export interface CoilCoil {
  coil_no: string;
  coil_thk_mm: Numeric | null;
  coil_width_mm: Numeric | null;
  created_at: Generated<Timestamp>;
  current_process_id: number | null;
  customer_id: number | null;
  grade_code: string | null;
  heat_no: string | null;
  next_dest: string | null;
  nominal_width_mm: Numeric | null;
  parent_coil_no: string | null;
  status: Generated<string>;
  surface_finish: string | null;
  tenant_id: Generated<string>;
  weight_mt: Numeric | null;
}

export interface ConfigRulesetVersion {
  id: Generated<number>;
  published_at: Generated<Timestamp | null>;
  published_by: string | null;
  version: Generated<number>;
}

export interface ConfigValidationRule {
  applies_when: Json | null;
  field_id: string;
  is_active: Generated<boolean>;
  machine_code: string | null;
  params: Json;
  process_code: string | null;
  rule_id: Generated<string>;
  rule_type: string;
  severity: string;
  updated_at: Generated<Timestamp | null>;
  updated_by: string | null;
}

export interface DashboardUsers {
  app_id: Generated<string>;
  email: string;
  password_hash: string;
  time_joined: Int8;
  user_id: string;
}

export interface DashboardUserSessions {
  app_id: Generated<string>;
  expiry: Int8;
  session_id: string;
  time_created: Int8;
  user_id: string;
}

export interface EmailpasswordPswdResetTokens {
  app_id: Generated<string>;
  email: string | null;
  token: string;
  token_expiry: Int8;
  user_id: string;
}

export interface EmailpasswordUsers {
  app_id: Generated<string>;
  email: string;
  password_hash: string;
  time_joined: Int8;
  user_id: string;
}

export interface EmailpasswordUserToTenant {
  app_id: Generated<string>;
  email: string;
  tenant_id: Generated<string>;
  user_id: string;
}

export interface EmailverificationTokens {
  app_id: Generated<string>;
  email: string;
  tenant_id: Generated<string>;
  token: string;
  token_expiry: Int8;
  user_id: string;
}

export interface EmailverificationVerifiedEmails {
  app_id: Generated<string>;
  email: string;
  user_id: string;
}

export interface JwtSigningKeys {
  algorithm: string;
  app_id: Generated<string>;
  created_at: Int8 | null;
  key_id: string;
  key_string: string;
}

export interface KeyValue {
  app_id: Generated<string>;
  created_at_time: Int8 | null;
  name: string;
  tenant_id: Generated<string>;
  value: string | null;
}

export interface MasterCrmSubProcess {
  machine_code: string;
  name: string;
  sub_process_code: string;
}

export interface MasterCustomer {
  customer_code: string;
  customer_id: Generated<number>;
  customer_name: string;
  is_active: Generated<boolean>;
  tenant_id: Generated<string>;
}

export interface MasterDefectCode {
  applies_to: string | null;
  defect_code: string;
  description: string;
  is_active: Generated<boolean>;
  symbol: string | null;
  tenant_id: Generated<string>;
}

export interface MasterFurnace {
  code: string;
  furnace_id: number;
  furnace_type: Generated<string | null>;
  name: string | null;
  tenant_id: Generated<string>;
}

export interface MasterGrade {
  acid_pct_max: Numeric | null;
  acid_pct_min: Numeric | null;
  description: string | null;
  grade_code: string;
  grade_family: string | null;
  is_active: Generated<boolean>;
  pkl_speed_max: Numeric | null;
  pkl_speed_min: Numeric | null;
  tenant_id: Generated<string>;
}

export interface MasterGradeSpec {
  customer_id: number | null;
  elongation_pct_min: Numeric | null;
  grade_code: string;
  hardness_hrb_max: Numeric | null;
  hardness_hrb_min: Numeric | null;
  ra_um_max: Numeric | null;
  spec_id: Generated<number>;
  tenant_id: Generated<string>;
  uts_nmm2_max: Numeric | null;
  uts_nmm2_min: Numeric | null;
}

export interface MasterLineArea {
  area_code: string;
  dpr_area_label: string;
  is_dpr_reported: Generated<boolean>;
  name: string;
  operating_minutes_base: Generated<number>;
  process_code: string | null;
  sort_order: number;
}

export interface MasterMachine {
  auto_boundary_handover: boolean | null;
  capacity_mt: Numeric | null;
  department: string | null;
  machine_code: string;
  machine_status: Generated<string>;
  machine_type: Generated<string | null>;
  name: string;
  ocr_min_confidence: Numeric | null;
  process_code: string | null;
  process_id: number | null;
}

export interface MasterMachineCrewRoster {
  created_at: Generated<Timestamp>;
  crew_id: Generated<Int8>;
  is_active: Generated<boolean>;
  machine_code: string;
  member_name: string;
  role_label: string;
  updated_at: Generated<Timestamp>;
}

export interface MasterOperator {
  emp_code: string;
  full_name: string;
  is_active: Generated<boolean>;
  operator_id: Generated<number>;
  tenant_id: Generated<string>;
}

export interface MasterProcess {
  code: string;
  has_mill_type: Generated<boolean>;
  name: string;
  process_id: number;
  seq_no: number;
  tenant_id: Generated<string>;
}

export interface MasterRouteCode {
  display_label: string;
  machine_code: string | null;
  process_code: string | null;
  route_code: string;
  seq_hint: Generated<number>;
  sub_process: string | null;
}

export interface MasterRpOilGrade {
  description: string | null;
  rp_oil_grade: string;
  tenant_id: Generated<string>;
}

export interface MasterShift {
  end_time: string;
  name: string;
  shift_code: string;
  start_time: string;
  tenant_id: Generated<string>;
}

export interface MasterStoppageCategory {
  agency_code: string | null;
  category_code: string;
  dpr_category: string | null;
  label: string;
  requires_breakdown_code: Generated<boolean>;
}

export interface MasterStoppageCode {
  agency_code: string | null;
  category: string;
  description: string;
  dpr_category: string | null;
  is_active: Generated<boolean>;
  is_planned: Generated<boolean>;
  stoppage_code: string;
  tenant_id: Generated<string>;
}

export interface MasterSurfaceFinish {
  description: string | null;
  surface_finish: string;
  tenant_id: Generated<string>;
}

export interface OauthClients {
  app_id: string;
  client_id: string;
  client_secret: string | null;
  enable_refresh_token_rotation: boolean;
  is_client_credentials_only: boolean;
}

export interface OauthLogoutChallenges {
  app_id: Generated<string>;
  challenge: string;
  client_id: string;
  post_logout_redirect_uri: string | null;
  session_handle: string | null;
  state: string | null;
  time_created: Int8;
}

export interface OauthM2mTokens {
  app_id: Generated<string>;
  client_id: string;
  exp: Int8;
  iat: Int8;
}

export interface OauthSessions {
  app_id: Generated<string | null>;
  client_id: string;
  exp: Int8;
  external_refresh_token: string | null;
  gid: string;
  internal_refresh_token: string | null;
  jti: string;
  session_handle: string | null;
}

export interface PasswordlessCodes {
  app_id: Generated<string>;
  code_id: string;
  created_at: Int8;
  device_id_hash: string;
  link_code_hash: string;
  tenant_id: Generated<string>;
}

export interface PasswordlessDevices {
  app_id: Generated<string>;
  device_id_hash: string;
  email: string | null;
  failed_attempts: number;
  link_code_salt: string;
  phone_number: string | null;
  tenant_id: Generated<string>;
}

export interface PasswordlessUsers {
  app_id: Generated<string>;
  email: string | null;
  phone_number: string | null;
  time_joined: Int8;
  user_id: string;
}

export interface PasswordlessUserToTenant {
  app_id: Generated<string>;
  email: string | null;
  phone_number: string | null;
  tenant_id: Generated<string>;
  user_id: string;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface PgmigrationsM1 {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface PlanningCoilPlan {
  coil_no: string | null;
  coil_plan_id: Generated<Int8>;
  plan_order_id: Int8 | null;
  planned_date: Timestamp | null;
  planned_process_id: number | null;
  seq_no: number | null;
  tenant_id: Generated<string>;
}

export interface PlanningImportBatch {
  error_count: Generated<number | null>;
  errors_json: Json | null;
  file_name: string | null;
  import_batch_id: Generated<Int8>;
  imported_at: Generated<Timestamp>;
  imported_by: number | null;
  row_count: number | null;
  source: string;
  status: Generated<string>;
  tenant_id: Generated<string>;
}

export interface PlanningOrderJourney {
  coil_no: string;
  created_at: Generated<Timestamp>;
  current_step_no: Generated<number>;
  journey_id: Generated<Int8>;
  route_raw: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PlanningOrderJourneyStep {
  completed_at: Timestamp | null;
  display_label: string;
  journey_id: Int8;
  machine_code: string | null;
  process_code: string | null;
  queue_batch_id: Int8 | null;
  route_code: string;
  started_at: Timestamp | null;
  status: Generated<string>;
  step_id: Generated<Int8>;
  step_no: number;
  sub_process: string | null;
}

export interface PlanningPlanOrder {
  customer_id: number | null;
  due_date: Timestamp | null;
  grade_code: string | null;
  import_batch_id: Int8 | null;
  plan_order_id: Generated<Int8>;
  planned_qty_mt: Numeric | null;
  sap_order_no: string | null;
  surface_finish: string | null;
  target_thk_mm: Numeric | null;
  target_width_mm: Numeric | null;
  tenant_id: Generated<string>;
}

export interface PlanningPpcBatch {
  active_rolling_pass_no: Generated<number>;
  batch_id: Generated<Int8>;
  batch_number: string;
  coil_count: Generated<number | null>;
  coil_no: string;
  customer_name: string;
  destination: string | null;
  finish_thk_mm: Numeric | null;
  from_work_center: string | null;
  grade_code: string;
  import_batch_id: Int8 | null;
  import_remark: string | null;
  imported_at: Generated<Timestamp>;
  input_thk_mm: Numeric;
  item_no: string | null;
  machine_allocated: Generated<boolean>;
  machine_code: string;
  max_thk_tol_mm: Numeric | null;
  min_thk_tol_mm: Numeric | null;
  sp_ra_max_um: Numeric | null;
  sp_ra_min_um: Numeric | null;
  plan_date: Timestamp;
  ppc_remarks: string | null;
  ppc_reroll_flag: Generated<boolean | null>;
  ppc_thk_mm: Numeric;
  ppc_weight_mt: Numeric;
  process_route_canonical: string | null;
  process_route_raw: string | null;
  queue_seq: number | null;
  raw_row_json: Json | null;
  roll_finish: string | null;
  sap_order_no: string | null;
  shift_code: string;
  slit_id: string | null;
  sub_process: string;
  to_work_center: string | null;
  width_mm: Numeric;
}

export interface PlanningPpcRollingPassPlan {
  batch_id: Int8;
  is_required: Generated<boolean>;
  pass_no: number;
  plan_id: Generated<Int8>;
  roll_finish: string | null;
  target_thk_mm: Numeric | null;
}

export interface PlanningProductionTarget {
  area_code: string;
  created_at: Generated<Timestamp>;
  period: Timestamp;
  target_id: Generated<Int8>;
  target_mt: Numeric | null;
  target_rate: Numeric | null;
}

export interface PlanningQueueHandoff {
  created_at: Generated<Timestamp>;
  handoff_id: Generated<Int8>;
  journey_id: Int8;
  source: Generated<string>;
  source_step_id: Int8;
  target_batch_id: Int8 | null;
  target_step_no: number;
}

export interface RolePermissions {
  app_id: Generated<string>;
  permission: string;
  role: string;
}

export interface Roles {
  app_id: Generated<string>;
  role: string;
}

export interface SamlClaims {
  app_id: Generated<string>;
  claims: string;
  client_id: string;
  code: string;
  created_at: Int8;
  expires_at: Int8;
  tenant_id: Generated<string>;
}

export interface SamlClients {
  allow_idp_initiated_login: Generated<boolean>;
  app_id: Generated<string>;
  client_id: string;
  client_secret: string | null;
  created_at: Int8;
  default_redirect_uri: string;
  enable_request_signing: Generated<boolean>;
  idp_entity_id: string;
  idp_signing_certificate: string;
  redirect_uris: string;
  sso_login_url: string;
  tenant_id: Generated<string>;
  updated_at: Int8;
}

export interface SamlRelayState {
  app_id: Generated<string>;
  client_id: string;
  created_at: Int8;
  expires_at: Int8;
  redirect_uri: string;
  relay_state: string;
  state: string | null;
  tenant_id: Generated<string>;
}

export interface SecurityAppUser {
  created_at: Generated<Timestamp>;
  email: string | null;
  emp_code: string | null;
  full_name: string;
  pin_failed_attempts: Generated<number>;
  pin_hash: string | null;
  pin_locked_until: Timestamp | null;
  status: Generated<string>;
  supertokens_user_id: string | null;
  tenant_id: Generated<string>;
  user_id: Generated<number>;
  username: string;
}

export interface SecurityDeviceRegistration {
  device_id: string;
  last_heartbeat: Timestamp | null;
  process_code: string;
  registered_at: Generated<Timestamp>;
  tenant_id: Generated<string>;
}

export interface SecurityLineAccess {
  access_level: Generated<string>;
  process_id: number;
  tenant_id: Generated<string>;
  user_id: number;
}

export interface SecurityMachineAccess {
  access_level: Generated<string>;
  assigned_at: Generated<Timestamp>;
  assigned_by: Int8 | null;
  machine_code: string;
  user_id: Int8;
}

export interface SecurityRole {
  description: string | null;
  role_id: number;
  role_name: string;
  tenant_id: Generated<string>;
}

export interface SecurityTenant {
  created_at: Generated<Timestamp>;
  name: string;
  status: Generated<string>;
  tenant_id: string;
}

export interface SecurityTenantConfig {
  branding: Json | null;
  config_version: Generated<number>;
  cost_rate_ownership: string | null;
  deployment_mode: Generated<string>;
  enabled_modules: Json | null;
  flags: Generated<Json>;
  isolation_level: Generated<string>;
  latency_target_seconds: number | null;
  retention_policy: Json | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SecurityUserRole {
  role_id: number;
  tenant_id: Generated<string>;
  user_id: number;
}

export interface SessionAccessTokenSigningKeys {
  app_id: Generated<string>;
  created_at_time: Int8;
  value: string | null;
}

export interface SessionInfo {
  app_id: Generated<string>;
  created_at_time: Int8;
  expires_at: Int8;
  jwt_user_payload: string | null;
  refresh_token_hash_2: string;
  session_data: string | null;
  session_handle: string;
  tenant_id: Generated<string>;
  use_static_key: boolean;
  user_id: string;
}

export interface TenantConfigs {
  app_id: Generated<string>;
  connection_uri_domain: Generated<string>;
  core_config: string | null;
  email_password_enabled: boolean | null;
  is_first_factors_null: boolean | null;
  passwordless_enabled: boolean | null;
  tenant_id: Generated<string>;
  third_party_enabled: boolean | null;
}

export interface TenantFirstFactors {
  app_id: Generated<string>;
  connection_uri_domain: Generated<string>;
  factor_id: string;
  tenant_id: Generated<string>;
}

export interface TenantRequiredSecondaryFactors {
  app_id: Generated<string>;
  connection_uri_domain: Generated<string>;
  factor_id: string;
  tenant_id: Generated<string>;
}

export interface Tenants {
  app_id: Generated<string>;
  created_at_time: Int8 | null;
  tenant_id: Generated<string>;
}

export interface TenantThirdpartyProviderClients {
  additional_config: string | null;
  app_id: Generated<string>;
  client_id: string;
  client_secret: string | null;
  client_type: Generated<string>;
  connection_uri_domain: Generated<string>;
  force_pkce: boolean | null;
  scope: string[] | null;
  tenant_id: Generated<string>;
  third_party_id: string;
}

export interface TenantThirdpartyProviders {
  app_id: Generated<string>;
  authorization_endpoint: string | null;
  authorization_endpoint_query_params: string | null;
  connection_uri_domain: Generated<string>;
  jwks_uri: string | null;
  name: string | null;
  oidc_discovery_endpoint: string | null;
  require_email: boolean | null;
  tenant_id: Generated<string>;
  third_party_id: string;
  token_endpoint: string | null;
  token_endpoint_body_params: string | null;
  user_info_endpoint: string | null;
  user_info_endpoint_headers: string | null;
  user_info_endpoint_query_params: string | null;
  user_info_map_from_id_token_payload_email: string | null;
  user_info_map_from_id_token_payload_email_verified: string | null;
  user_info_map_from_id_token_payload_user_id: string | null;
  user_info_map_from_user_info_endpoint_email: string | null;
  user_info_map_from_user_info_endpoint_email_verified: string | null;
  user_info_map_from_user_info_endpoint_user_id: string | null;
}

export interface ThirdpartyUsers {
  app_id: Generated<string>;
  email: string;
  third_party_id: string;
  third_party_user_id: string;
  time_joined: Int8;
  user_id: string;
}

export interface ThirdpartyUserToTenant {
  app_id: Generated<string>;
  tenant_id: Generated<string>;
  third_party_id: string;
  third_party_user_id: string;
  user_id: string;
}

export interface TotpUsedCodes {
  app_id: Generated<string>;
  code: string;
  created_time_ms: Int8;
  expiry_time_ms: Int8;
  is_valid: boolean;
  tenant_id: Generated<string>;
  user_id: string;
}

export interface TotpUserDevices {
  app_id: Generated<string>;
  created_at: Int8 | null;
  device_name: string;
  period: number;
  secret_key: string;
  skew: number;
  user_id: string;
  verified: boolean;
}

export interface TotpUsers {
  app_id: Generated<string>;
  user_id: string;
}

export interface TxnAnnCharge {
  base_no: string | null;
  charge_no: string;
  charge_wt_mt: Numeric | null;
  cumm_loading_mt: Numeric | null;
  cumm_unloading_mt: Numeric | null;
  dew_point_h2: Numeric | null;
  dew_point_n2: Numeric | null;
  exp_unloading_time: Timestamp | null;
  furnace_id: number | null;
  grade_code: string | null;
  loading_mt: Numeric | null;
  no_of_coils: number | null;
  oxygen_pct: Numeric | null;
  prod_date: Timestamp | null;
  shift_code: string | null;
  shift_log_id: Int8;
  status: string | null;
  temperature_degc: Numeric | null;
  tenant_id: Generated<string>;
  unloading_mt: Numeric | null;
  unloading_wt_mt: Numeric | null;
}

export interface TxnAnnChargeCoil {
  charge_no: string;
  coil_no: string;
  seq_no: number | null;
  tenant_id: Generated<string>;
}

export interface TxnCrmOrder {
  batch_id: Int8;
  batch_number: string;
  coil_no: string;
  combined_group_id: string | null;
  created_at: Generated<Timestamp>;
  customer_name: string;
  grade_code: string;
  input_thk_mm: Numeric | null;
  logged_in_user_id: number | null;
  order_id: Generated<Int8>;
  ppc_thk_mm: Numeric;
  ppc_weight_mt: Numeric;
  prod_date: Timestamp | null;
  prod_duration_min: number | null;
  prod_end_at: Timestamp | null;
  prod_start_at: Timestamp | null;
  production_day: Timestamp | null;
  shift_code: string | null;
  shift_log_id: Int8 | null;
  slit_id: string | null;
  status: Generated<string>;
  sub_process: string;
  updated_at: Generated<Timestamp>;
  width_mm: Numeric;
}

export interface TxnCrmRollChange {
  change_id: Generated<Int8>;
  changed_at: Generated<Timestamp>;
  new_roll_code: string | null;
  new_roll_no: string;
  operator_id: number | null;
  order_id: Int8;
  prev_roll_code: string | null;
  prev_roll_no: string | null;
  reason_text: string | null;
  roll_position: string;
}

export interface TxnCrmRolling {
  actual_weight_mt: Numeric | null;
  actual_weight_photo_hash: string | null;
  actual_weight_source: string | null;
  associate_rw: string | null;
  destination: string | null;
  destination_override: Generated<boolean | null>;
  dtr: Numeric | null;
  etr: Numeric | null;
  final_thk_mm: Numeric | null;
  ocr_confidence: Numeric | null;
  ocr_raw_text: string | null;
  order_id: Int8;
  prod_date: Timestamp | null;
  rerolling: Generated<boolean | null>;
  roll_finish: string | null;
  roll_in_code: string | null;
  roll_in_no: string | null;
  roll_out_code: string | null;
  roll_out_no: string | null;
  shift_code: string | null;
  total_passes: number | null;
}

export interface TxnCrmRollingPass {
  order_id: Int8;
  pass_id: Generated<Int8>;
  pass_no: number;
  thickness_mm: Numeric;
}

export interface TxnCrmShiftSummary {
  coolant_press_kgcm2: Numeric | null;
  coolant_temp_degc: Numeric | null;
  scrap_kg: Numeric | null;
  shift_log_id: Int8;
  submitted_at: Timestamp | null;
  submitted_by: number | null;
  summary_id: Generated<Int8>;
  total_prod_mt: Numeric | null;
  total_reroll_mt: Numeric | null;
  total_rolling_mt: Numeric | null;
  total_skinpass_mt: Numeric | null;
}

export interface TxnCrmSkinpass {
  actual_weight_mt: Numeric | null;
  actual_weight_photo_hash: string | null;
  actual_weight_source: string | null;
  ann_hard: Numeric | null;
  load_max_t: Numeric | null;
  load_min_t: Numeric | null;
  ocr_confidence: Numeric | null;
  ocr_raw_text: string | null;
  operating_mode: string | null;
  order_id: Int8;
  output_thk_mm: Numeric | null;
  rw_tension_1: Numeric | null;
  rw_tension_2: Numeric | null;
  stretch_pct: Numeric | null;
}

export interface TxnDeskNotification {
  body: string;
  created_at: Generated<Timestamp>;
  handover_id: Int8 | null;
  kind: string;
  machine_code: string | null;
  notification_id: Generated<Int8>;
  payload: unknown;
  resolved_at: Timestamp | null;
  shift_log_id: Int8 | null;
  title: string;
  user_id: number;
}

export interface TxnDefectEntry {
  coil_no: string | null;
  defect_code: string;
  defect_id: Generated<Int8>;
  entry_id: Int8;
  location: string | null;
  process_id: number;
  prod_date: Timestamp | null;
  qty_mt: Numeric | null;
  shift_code: string | null;
  tenant_id: Generated<string>;
}

export interface TxnIdempotencyKey {
  created_at: Generated<Timestamp>;
  key: string;
  response_body: Json | null;
  response_status: number;
}

export interface TxnMachineHandover {
  accepted_at: Timestamp | null;
  batch_number: string | null;
  breakdown_code: string | null;
  breakdown_description: string | null;
  clarification_notes: string | null;
  created_at: Generated<Timestamp>;
  created_by_boundary: Generated<boolean>;
  downtime_minutes: number | null;
  handover_id: Generated<string>;
  handover_priority: Generated<string>;
  incoming_operator_id: number | null;
  incoming_prod_date: Timestamp;
  incoming_shift_code: string;
  machine_code: string;
  machine_status: string;
  maintenance_status: string | null;
  open_stoppages: Generated<Json>;
  order_id: Int8 | null;
  outgoing_operator_id: number;
  outgoing_prod_date: Timestamp;
  outgoing_shift_code: string;
  process_code: string;
  production_snapshot: Generated<Json>;
  queue_snapshot: Generated<Json>;
  remarks: string;
  status: Generated<string>;
}

export interface TxnMachineShiftSession {
  closed_at: Timestamp | null;
  machine_code: string;
  operator_user_id: number;
  override_id: Int8 | null;
  prod_date: Timestamp;
  session_id: Generated<Int8>;
  shift_code: string;
  shift_log_id: Int8 | null;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface TxnMachineStateEvent {
  batch_number: string | null;
  category_code: string | null;
  /**
   * Computed when ended_at is set: (ended_at - occurred_at) in minutes.
   */
  duration_min: Numeric | null;
  /**
   * Set when the paired *_ENDED event is recorded. NULL = event is still active.
   */
  ended_at: Timestamp | null;
  event_id: Generated<Int8>;
  /**
   * One of: RUNNING_STARTED, RUNNING_ENDED, STOPPAGE_STARTED, STOPPAGE_ENDED, IDLE_STARTED, IDLE_ENDED, MAINTENANCE_STARTED, MAINTENANCE_ENDED
   */
  event_type: string;
  machine_code: string;
  meta: Json | null;
  occurred_at: Generated<Timestamp>;
  operator_id: number | null;
  order_id: Int8 | null;
  reason: string | null;
  shift_code: string | null;
  tenant_id: Generated<string>;
}

export interface TxnOrderMachineTransfer {
  assigned_by: number | null;
  batch_number: string;
  destination_machine_code: string;
  order_id: Int8 | null;
  reason: string | null;
  source_machine_code: string;
  sub_process: string;
  transfer_id: Generated<Int8>;
  transfer_type: Generated<string>;
  transferred_at: Generated<Timestamp>;
}

export interface TxnOrderRejection {
  created_at: Generated<Timestamp>;
  defect_codes: Json | null;
  operator_id: number;
  order_id: Int8;
  rejection_id: Generated<Int8>;
  rejection_reason: string;
  remarks: string;
  tenant_id: Generated<string>;
}

export interface TxnOrderRemark {
  created_at: Generated<Timestamp>;
  defect_codes: Json | null;
  operator_id: number | null;
  order_id: Int8;
  remark_id: Generated<Int8>;
  text: string;
}

export interface TxnOrderShiftAttribution {
  attribution_id: Generated<Int8>;
  breakdown_minutes: Generated<number>;
  machine_code: string;
  order_id: Int8;
  prod_date: Timestamp;
  production_mt: Generated<Numeric>;
  runtime_minutes: Generated<number>;
  shift_code: string;
  shift_log_id: Int8;
  stoppage_minutes: Generated<number>;
}

export interface TxnProdCrs {
  actual_thk_front_mm: Numeric | null;
  actual_thk_rear_mm: Numeric | null;
  actual_width_mm: Numeric | null;
  camber_waviness: string | null;
  coating_wt_br: Numeric | null;
  coating_wt_matt: Numeric | null;
  coil_no: string;
  coil_width_mm: Numeric | null;
  elongation_pct: Numeric | null;
  entry_id: Generated<Int8>;
  for_ctl_mt: Numeric | null;
  hardness_hrb: Numeric | null;
  hardness_vpn: Numeric | null;
  hold_mt: Numeric | null;
  ib_tiecv: string | null;
  nominal_thk_mm: Numeric | null;
  output_wt_mt: Numeric | null;
  prod_date: Timestamp | null;
  ra_um: Numeric | null;
  rejection_id_mt: Numeric | null;
  rejection_od_mt: Numeric | null;
  remarks: string | null;
  rp_oil_grade: string | null;
  rz_um: Numeric | null;
  shift_code: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  slit_no: string | null;
  tenant_id: Generated<string>;
  uts_nmm2: Numeric | null;
  ysr_burr: string | null;
}

export interface TxnProdCrsSlit {
  child_coil_no: string | null;
  entry_id: Int8;
  slit_id: Generated<Int8>;
  slot: string | null;
  tenant_id: Generated<string>;
  width_mm: Numeric | null;
}

export interface TxnProdCtl {
  actual_length_mm: Numeric | null;
  coil_no: string;
  entry_id: Generated<Int8>;
  estimated_suppressed: string | null;
  hold_mt: Numeric | null;
  low_speed: string | null;
  no_bundles: number | null;
  no_pieces: number | null;
  nominal_set_length_mm: Numeric | null;
  prod_date: Timestamp | null;
  rejection_mt: Numeric | null;
  remarks: string | null;
  shift_code: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  tenant_id: Generated<string>;
  thk_mm: Numeric | null;
  time_from: string | null;
  time_to: string | null;
  total_prod_mt: Numeric | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
}

export interface TxnProdHrs {
  actual_slit_width_from_mm: Numeric | null;
  actual_slit_width_to_mm: Numeric | null;
  actual_width_mm: Numeric | null;
  coil_no: string;
  entry_id: Generated<Int8>;
  nominal_thk_mm: Numeric | null;
  nominal_width_mm: Numeric | null;
  prod_date: Timestamp | null;
  remarks: string | null;
  scrap_mt: Numeric | null;
  scrap_pct: Numeric | null;
  shift_code: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  tenant_id: Generated<string>;
  time_from: string | null;
  time_to: string | null;
  weight_mt: Numeric | null;
}

export interface TxnProdHrsSlit {
  child_coil_no: string | null;
  entry_id: Int8;
  slit_id: Generated<Int8>;
  slot: string;
  taper: string | null;
  tenant_id: Generated<string>;
  thk_mm: Numeric | null;
  width_mm: Numeric | null;
}

export interface TxnProdPkl {
  coil_no: string;
  entry_id: Generated<Int8>;
  heat_no: string | null;
  leader_end: string | null;
  line_speed_mpm: Numeric | null;
  prod_date: Timestamp | null;
  remarks: string | null;
  shift_code: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  source: string | null;
  tenant_id: Generated<string>;
  thk_mm: Numeric | null;
  time_from: string | null;
  time_to: string | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
  wip: string | null;
}

export interface TxnProdPklChart {
  acid_strength_pct: Numeric | null;
  burner_pressure_kgcm2: Numeric | null;
  chart_id: Generated<Int8>;
  chart_time: string;
  dosage_acid: Numeric | null;
  dosage_inhibitor: Numeric | null;
  dosage_water: Numeric | null;
  hot_air_temp_degc: Numeric | null;
  iron_strength_pct: Numeric | null;
  rinse_acid_pct: Numeric | null;
  rinse_cl: Numeric | null;
  rinse_flow: Numeric | null;
  rinse_iron_pct: Numeric | null;
  rinse_ph: Numeric | null;
  rinse_temp_degc: Numeric | null;
  shift_log_id: Int8;
  steam_inlet_kgcm2: Numeric | null;
  steam_outlet_kgcm2: Numeric | null;
  tank_level: Numeric | null;
  tank_no: number | null;
  tank_temp_degc: Numeric | null;
  tenant_id: Generated<string>;
}

export interface TxnProdRwd {
  coil_no: string;
  entry_id: Generated<Int8>;
  output_thk_mm: Numeric | null;
  prod_date: Timestamp | null;
  remarks: string | null;
  rw_tension_1_kg: Numeric | null;
  rw_tension_2_kg: Numeric | null;
  rw_tension_3_kg: Numeric | null;
  shift_code: string | null;
  shift_log_id: Int8;
  sl_no: number | null;
  surface_finish: string | null;
  tenant_id: Generated<string>;
  thk_mm: Numeric | null;
  time_from: string | null;
  time_to: string | null;
  weight_mt: Numeric | null;
  width_mm: Numeric | null;
}

export interface TxnSessionCrew {
  created_at: Generated<Timestamp>;
  crew_id: Int8;
  session_crew_id: Generated<Int8>;
  session_id: Int8;
  tenant_id: Generated<string>;
}

export interface TxnShiftEventAudit {
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string | null;
  event_id: Generated<Int8>;
  event_type: string;
  machine_code: string | null;
  payload: Generated<Json>;
  user_id: number | null;
}

export interface TxnShiftLog {
  approved_at: Timestamp | null;
  approver_id: number | null;
  line_incharge_id: number | null;
  mill_type: string | null;
  process_id: number;
  prod_date: Timestamp;
  /**
   * The active ruleset version at the time of submission
   */
  ruleset_version: number | null;
  shift_code: string;
  shift_log_id: Generated<Int8>;
  shift_manager_id: number | null;
  state: Generated<string>;
  submitted_at: Timestamp | null;
  target_mt: Numeric | null;
  tenant_id: Generated<string>;
  total_prod_mt: Numeric | null;
}

export interface TxnShiftOverrideAudit {
  created_at: Generated<Timestamp>;
  machine_code: string | null;
  override_id: Generated<Int8>;
  prod_date: Timestamp;
  reason_code: string;
  reason_detail: string | null;
  selected_shift_code: string;
  user_id: number;
}

export interface TxnStoppage {
  breakdown_code: string | null;
  category_code: string;
  duration_min: number | null;
  end_at: Timestamp | null;
  machine_code: string | null;
  operator_id: number | null;
  order_id: Int8 | null;
  prod_date: Timestamp | null;
  remarks: string | null;
  shift_code: string | null;
  shift_log_id: Int8 | null;
  start_at: Generated<Timestamp>;
  stoppage_id: Generated<Int8>;
  tenant_id: Generated<string>;
}

export interface TxnValidationOverrides {
  created_at: Generated<Timestamp>;
  field_path: string;
  override_by: number;
  override_id: Generated<Int8>;
  reason: string;
  shift_log_id: Int8;
}

export interface UseridMapping {
  app_id: Generated<string>;
  external_user_id: string;
  external_user_id_info: string | null;
  supertokens_user_id: string;
}

export interface UserLastActive {
  app_id: Generated<string>;
  last_active_time: Int8 | null;
  user_id: string;
}

export interface UserMetadata {
  app_id: Generated<string>;
  user_id: string;
  user_metadata: string;
}

export interface UserRoles {
  app_id: Generated<string>;
  role: string;
  tenant_id: Generated<string>;
  user_id: string;
}

export interface WebauthnAccountRecoveryTokens {
  app_id: Generated<string>;
  email: string;
  expires_at: Int8;
  tenant_id: Generated<string>;
  token: string;
  user_id: string;
}

export interface WebauthnCredentials {
  app_id: Generated<string>;
  counter: Int8;
  created_at: Int8;
  id: string;
  public_key: Buffer;
  rp_id: string;
  transports: string;
  updated_at: Int8;
  user_id: string | null;
}

export interface WebauthnGeneratedOptions {
  app_id: Generated<string>;
  challenge: string;
  created_at: Int8;
  email: string | null;
  expires_at: Int8;
  id: string;
  origin: string;
  rp_id: string;
  rp_name: string;
  tenant_id: Generated<string>;
  user_presence_required: Generated<boolean>;
  user_verification: Generated<string>;
}

export interface WebauthnUsers {
  app_id: Generated<string>;
  email: string;
  rp_id: string;
  time_joined: Int8;
  user_id: string;
}

export interface WebauthnUserToTenant {
  app_id: Generated<string>;
  email: string;
  tenant_id: Generated<string>;
  user_id: string;
}

export interface DB {
  all_auth_recipe_users: AllAuthRecipeUsers;
  app_id_to_user_id: AppIdToUserId;
  apps: Apps;
  "audit.audit_log": AuditAuditLog;
  "audit.dpr_month_lock": AuditDprMonthLock;
  "audit.export_job": AuditExportJob;
  "audit.lineage_ref": AuditLineageRef;
  bulk_import_users: BulkImportUsers;
  "canon.equipment_node": CanonEquipmentNode;
  "canon.event": CanonEvent;
  "canon.production_count": CanonProductionCount;
  "coil.coil": CoilCoil;
  "config.ruleset_version": ConfigRulesetVersion;
  "config.validation_rule": ConfigValidationRule;
  dashboard_user_sessions: DashboardUserSessions;
  dashboard_users: DashboardUsers;
  emailpassword_pswd_reset_tokens: EmailpasswordPswdResetTokens;
  emailpassword_user_to_tenant: EmailpasswordUserToTenant;
  emailpassword_users: EmailpasswordUsers;
  emailverification_tokens: EmailverificationTokens;
  emailverification_verified_emails: EmailverificationVerifiedEmails;
  jwt_signing_keys: JwtSigningKeys;
  key_value: KeyValue;
  "master.crm_sub_process": MasterCrmSubProcess;
  "master.customer": MasterCustomer;
  "master.defect_code": MasterDefectCode;
  "master.furnace": MasterFurnace;
  "master.grade": MasterGrade;
  "master.grade_spec": MasterGradeSpec;
  "master.line_area": MasterLineArea;
  "master.machine": MasterMachine;
  "master.machine_crew_roster": MasterMachineCrewRoster;
  "master.operator": MasterOperator;
  "master.process": MasterProcess;
  "master.route_code": MasterRouteCode;
  "master.rp_oil_grade": MasterRpOilGrade;
  "master.shift": MasterShift;
  "master.stoppage_category": MasterStoppageCategory;
  "master.stoppage_code": MasterStoppageCode;
  "master.surface_finish": MasterSurfaceFinish;
  oauth_clients: OauthClients;
  oauth_logout_challenges: OauthLogoutChallenges;
  oauth_m2m_tokens: OauthM2mTokens;
  oauth_sessions: OauthSessions;
  passwordless_codes: PasswordlessCodes;
  passwordless_devices: PasswordlessDevices;
  passwordless_user_to_tenant: PasswordlessUserToTenant;
  passwordless_users: PasswordlessUsers;
  pgmigrations: Pgmigrations;
  pgmigrations_m1: PgmigrationsM1;
  "planning.coil_plan": PlanningCoilPlan;
  "planning.import_batch": PlanningImportBatch;
  "planning.order_journey": PlanningOrderJourney;
  "planning.order_journey_step": PlanningOrderJourneyStep;
  "planning.plan_order": PlanningPlanOrder;
  "planning.ppc_batch": PlanningPpcBatch;
  "planning.ppc_rolling_pass_plan": PlanningPpcRollingPassPlan;
  "planning.production_target": PlanningProductionTarget;
  "planning.queue_handoff": PlanningQueueHandoff;
  role_permissions: RolePermissions;
  roles: Roles;
  saml_claims: SamlClaims;
  saml_clients: SamlClients;
  saml_relay_state: SamlRelayState;
  "security.app_user": SecurityAppUser;
  "security.device_registration": SecurityDeviceRegistration;
  "security.line_access": SecurityLineAccess;
  "security.machine_access": SecurityMachineAccess;
  "security.role": SecurityRole;
  "security.tenant": SecurityTenant;
  "security.tenant_config": SecurityTenantConfig;
  "security.user_role": SecurityUserRole;
  session_access_token_signing_keys: SessionAccessTokenSigningKeys;
  session_info: SessionInfo;
  tenant_configs: TenantConfigs;
  tenant_first_factors: TenantFirstFactors;
  tenant_required_secondary_factors: TenantRequiredSecondaryFactors;
  tenant_thirdparty_provider_clients: TenantThirdpartyProviderClients;
  tenant_thirdparty_providers: TenantThirdpartyProviders;
  tenants: Tenants;
  thirdparty_user_to_tenant: ThirdpartyUserToTenant;
  thirdparty_users: ThirdpartyUsers;
  totp_used_codes: TotpUsedCodes;
  totp_user_devices: TotpUserDevices;
  totp_users: TotpUsers;
  "txn.ann_charge": TxnAnnCharge;
  "txn.ann_charge_coil": TxnAnnChargeCoil;
  "txn.crm_order": TxnCrmOrder;
  "txn.crm_roll_change": TxnCrmRollChange;
  "txn.crm_rolling": TxnCrmRolling;
  "txn.crm_rolling_pass": TxnCrmRollingPass;
  "txn.crm_shift_summary": TxnCrmShiftSummary;
  "txn.crm_skinpass": TxnCrmSkinpass;
  "txn.defect_entry": TxnDefectEntry;
  "txn.desk_notification": TxnDeskNotification;
  "txn.idempotency_key": TxnIdempotencyKey;
  "txn.machine_handover": TxnMachineHandover;
  "txn.machine_shift_session": TxnMachineShiftSession;
  "txn.machine_state_event": TxnMachineStateEvent;
  "txn.order_machine_transfer": TxnOrderMachineTransfer;
  "txn.order_rejection": TxnOrderRejection;
  "txn.order_remark": TxnOrderRemark;
  "txn.order_shift_attribution": TxnOrderShiftAttribution;
  "txn.prod_crs": TxnProdCrs;
  "txn.prod_crs_slit": TxnProdCrsSlit;
  "txn.prod_ctl": TxnProdCtl;
  "txn.prod_hrs": TxnProdHrs;
  "txn.prod_hrs_slit": TxnProdHrsSlit;
  "txn.prod_pkl": TxnProdPkl;
  "txn.prod_pkl_chart": TxnProdPklChart;
  "txn.prod_rwd": TxnProdRwd;
  "txn.session_crew": TxnSessionCrew;
  "txn.shift_event_audit": TxnShiftEventAudit;
  "txn.shift_log": TxnShiftLog;
  "txn.shift_override_audit": TxnShiftOverrideAudit;
  "txn.stoppage": TxnStoppage;
  "txn.validation_overrides": TxnValidationOverrides;
  user_last_active: UserLastActive;
  user_metadata: UserMetadata;
  user_roles: UserRoles;
  userid_mapping: UseridMapping;
  webauthn_account_recovery_tokens: WebauthnAccountRecoveryTokens;
  webauthn_credentials: WebauthnCredentials;
  webauthn_generated_options: WebauthnGeneratedOptions;
  webauthn_user_to_tenant: WebauthnUserToTenant;
  webauthn_users: WebauthnUsers;
}
