-- =====================================================================
-- Zedral · M4 OEE & Downtime Intelligence — Reference Schema (PostgreSQL 15+)
-- Status: v1 for build (capture-agnostic OEE calc + Six-Big-Losses tree).
--         v1 bootstraps from M1 manual capture; PLC/OPC-UA auto-capture
--         future-proofed (deep-plan §5). Prediction hooks present, build
--         deferred (deep-plan §8).
-- Conventions: follows canonical DDL spec (02_CanonicalDataModel_Spec §5):
--   lower_snake_case · surrogate BIGINT ids · UUID tenant_id · TIMESTAMPTZ (UTC)
--   JSONB `ext` extension namespace · FK to canon.* · units embedded in column name.
-- Assumes the canonical core already exists:
--   canon.equipment_node(node_id)   -- ISA-95 hierarchy incl. WORK_CENTER & WORK_UNIT
--   canon.event(event_id)           -- Event Spine; state_event/downtime_event/production_count are specializations
--   canon.shift(shift_id)           -- shift/calendar (defines Planned Production Time)
--   canon.reason_code(reason_id, loss_category_ref, oee_component)  -- canonical reason taxonomy
--   canon.loss_category(category_id, oee_component)                 -- Six Big Losses (ISO 22400/TPM)
--   canon.state_model(state_id, is_planned, counts_as)             -- ISO 22400 state model
--   canon.cost_rate(rate_id ...)    -- effective-dated rates (D7)
-- SOFT-REFERENCE RULE: references to OTHER module schemas (e.g. ops.material in M3)
--   are plain BIGINT *_ref values with NO cross-schema hard FK, so canon/M4 stay
--   independent of M3. Hard FKs are used ONLY to canon.* — the same discipline M2/M3 use.
-- THE no-double-count anchor: oee.* rows carry the canonical event_id of the SAME
--   StateEvent / DowntimeEvent / ProductionCount that M2 (failure) and M3 (attainment)
--   read — M4 aggregates the OEE view, it never re-records the event.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS oee;
SET search_path = oee, canon, public;

-- ---------------------------------------------------------------------
-- 0. Enumerated types
-- ---------------------------------------------------------------------
CREATE TYPE oee.machine_state         AS ENUM ('RUNNING','MINOR_STOP','BREAKDOWN','SETUP','PLANNED_STOP','NOT_SCHEDULED');
CREATE TYPE oee.oee_component         AS ENUM ('AVAILABILITY','PERFORMANCE','QUALITY','NONE');
CREATE TYPE oee.big_loss              AS ENUM ('L1_BREAKDOWN','L2_SETUP','L3_MINOR_STOP','L4_REDUCED_SPEED','L5_DEFECT','L6_STARTUP_YIELD');
CREATE TYPE oee.planned_time_convention AS ENUM ('EXCLUDE_FROM_PPT','INSIDE_AVAILABILITY');
CREATE TYPE oee.ideal_cycle_source    AS ENUM ('NAMEPLATE','DEMONSTRATED_BEST','M3_PLAN_TARGET','MANUAL');
CREATE TYPE oee.capture_fidelity      AS ENUM ('MANUAL','HISTORIAN','AUTOMATIC');
CREATE TYPE oee.time_grain            AS ENUM ('HOUR','SHIFT','DAY');
CREATE TYPE oee.rank_basis            AS ENUM ('MINUTES','COST','UNITS');
CREATE TYPE oee.readiness_gate        AS ENUM ('REQUIRED','QUALITY','FIDELITY','HISTORY');

-- ---------------------------------------------------------------------
-- 1. Per-tenant OEE policy (the definitions-as-configuration switch, §4/§5)
-- ---------------------------------------------------------------------
CREATE TABLE oee.oee_config (
  tenant_id                 UUID PRIMARY KEY,
  micro_stop_threshold_sec  INT  NOT NULL DEFAULT 120 CHECK (micro_stop_threshold_sec > 0),  -- A/P seam (§5)
  planned_time_convention   oee.planned_time_convention NOT NULL DEFAULT 'EXCLUDE_FROM_PPT',
  default_ideal_source      oee.ideal_cycle_source NOT NULL DEFAULT 'DEMONSTRATED_BEST',
  teep_enabled              BOOLEAN NOT NULL DEFAULT TRUE,
  prediction_enabled        BOOLEAN NOT NULL DEFAULT FALSE,                                  -- future scope (§8), gated by readiness
  ext                       JSONB NOT NULL DEFAULT '{}'::jsonb
);
COMMENT ON TABLE  oee.oee_config IS 'Per-tenant OEE policy; planned-time convention, micro-stop seam, ideal-cycle default (deep-plan §4-5).';
COMMENT ON COLUMN oee.oee_config.planned_time_convention IS 'EXCLUDE_FROM_PPT=planned stops leave the denominator; INSIDE_AVAILABILITY=counted as planned downtime. Both ISO 22400-valid.';

-- ---------------------------------------------------------------------
-- 2. Per-work-unit OEE configuration (overrides + capture fidelity)
-- ---------------------------------------------------------------------
CREATE TABLE oee.work_unit_config (
  work_unit_config_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id                 UUID NOT NULL,
  work_unit_ref             BIGINT NOT NULL REFERENCES canon.equipment_node(node_id),
  micro_stop_threshold_sec  INT,                                  -- NULL = inherit tenant default
  capture_fidelity          oee.capture_fidelity NOT NULL DEFAULT 'MANUAL',
  micro_stops_observed      BOOLEAN NOT NULL DEFAULT FALSE,       -- drives the Fidelity readiness gate (§11)
  oee_relevant              BOOLEAN NOT NULL DEFAULT TRUE,
  ext                       JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (tenant_id, work_unit_ref)
);
COMMENT ON TABLE oee.work_unit_config IS 'Per-work-unit OEE settings; capture fidelity feeds the readiness/confidence model (§11, Principle 7).';

-- ---------------------------------------------------------------------
-- 3. Ideal cycle time / rated speed reference (the Performance denominator, §4)
--    Keyed by material x work-unit; versioned; material_ref is a SOFT reference.
-- ---------------------------------------------------------------------
CREATE TABLE oee.ideal_cycle (
  ideal_cycle_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id                 UUID NOT NULL,
  work_unit_ref             BIGINT NOT NULL REFERENCES canon.equipment_node(node_id),
  material_ref              BIGINT,                               -- SOFT ref to ops.material (M3) / canonical material; NULL = unit default
  grade_ref                 TEXT,                                 -- steel: grade x spec convenience key
  ideal_cycle_time_sec      NUMERIC CHECK (ideal_cycle_time_sec > 0),   -- discrete: time per unit
  rated_rate_per_hr         NUMERIC CHECK (rated_rate_per_hr > 0),      -- process: units (e.g. MT or m) per hour
  uom                       TEXT NOT NULL DEFAULT 'EA',
  source                    oee.ideal_cycle_source NOT NULL,
  is_calibrated             BOOLEAN NOT NULL DEFAULT FALSE,       -- FALSE -> flagged by Fidelity gate (§4 ideal-cycle problem)
  version                   INT NOT NULL DEFAULT 1,
  effective_from            DATE NOT NULL DEFAULT CURRENT_DATE,
  ext                       JSONB NOT NULL DEFAULT '{}'::jsonb,
  CHECK (ideal_cycle_time_sec IS NOT NULL OR rated_rate_per_hr IS NOT NULL)
);
CREATE INDEX ix_ideal_cycle_lookup ON oee.ideal_cycle (tenant_id, work_unit_ref, material_ref, effective_from DESC);
COMMENT ON TABLE oee.ideal_cycle IS 'Ideal cycle time / rated speed per material x work-unit (versioned). The honest Performance denominator (deep-plan §4).';

-- ---------------------------------------------------------------------
-- 4. OEE target (per asset/period) — drives variance & alerts
-- ---------------------------------------------------------------------
CREATE TABLE oee.oee_target (
  oee_target_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id                 UUID NOT NULL,
  work_unit_ref             BIGINT NOT NULL REFERENCES canon.equipment_node(node_id),
  target_oee                NUMERIC CHECK (target_oee BETWEEN 0 AND 1),
  target_availability       NUMERIC CHECK (target_availability BETWEEN 0 AND 1),
  target_performance        NUMERIC CHECK (target_performance BETWEEN 0 AND 1),
  target_quality            NUMERIC CHECK (target_quality BETWEEN 0 AND 1),
  effective_from            DATE NOT NULL DEFAULT CURRENT_DATE,
  ext                       JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX ix_oee_target ON oee.oee_target (tenant_id, work_unit_ref, effective_from DESC);

-- ---------------------------------------------------------------------
-- 5. State interval — raw canon.state_event resolved into clean, closed,
--    debounced intervals (the time model, §5). Specialises the Event Spine,
--    does NOT re-record it: state_event_ref points back to canon.event.
-- ---------------------------------------------------------------------
CREATE TABLE oee.state_interval (
  state_interval_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id                 UUID NOT NULL,
  work_unit_ref             BIGINT NOT NULL REFERENCES canon.equipment_node(node_id),
  state                     oee.machine_state NOT NULL,
  is_planned                BOOLEAN NOT NULL,
  counts_as                 oee.oee_component NOT NULL DEFAULT 'NONE',
  start_ts                  TIMESTAMPTZ NOT NULL,
  end_ts                    TIMESTAMPTZ,                          -- NULL = open (current) interval
  duration_sec              NUMERIC GENERATED ALWAYS AS (EXTRACT(EPOCH FROM (end_ts - start_ts))) STORED,
  is_micro_stop             BOOLEAN NOT NULL DEFAULT FALSE,       -- below micro-stop threshold -> Performance (L3)
  state_event_ref           BIGINT REFERENCES canon.event(event_id),   -- back-pointer to the Event Spine (no re-record)
  downtime_event_ref        BIGINT REFERENCES canon.event(event_id),   -- shared w/ M2 when the stop is a downtime
  ext                       JSONB NOT NULL DEFAULT '{}'::jsonb,
  CHECK (end_ts IS NULL OR end_ts >= start_ts)
);
CREATE INDEX ix_state_interval_wu_time ON oee.state_interval (tenant_id, work_unit_ref, start_ts);
CREATE INDEX ix_state_interval_open ON oee.state_interval (tenant_id, work_unit_ref) WHERE end_ts IS NULL;
COMMENT ON TABLE oee.state_interval IS 'Closed/debounced state intervals derived from canon.state_event; the Availability + micro-stop time base (deep-plan §5).';

-- ---------------------------------------------------------------------
-- 6. OEE interval — computed A/P/Q per work-unit x time bucket.
--    STORES QUANTITIES (not just ratios) so roll-ups SUM then divide (§4).
-- ---------------------------------------------------------------------
CREATE TABLE oee.oee_interval (
  oee_interval_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id                 UUID NOT NULL,
  work_unit_ref             BIGINT NOT NULL REFERENCES canon.equipment_node(node_id),
  shift_ref                 BIGINT REFERENCES canon.shift(shift_id),
  grain                     oee.time_grain NOT NULL DEFAULT 'SHIFT',
  bucket_start              TIMESTAMPTZ NOT NULL,
  bucket_end                TIMESTAMPTZ NOT NULL,
  -- time quantities (minutes)
  calendar_time_min         NUMERIC NOT NULL DEFAULT 0,
  planned_production_min    NUMERIC NOT NULL DEFAULT 0,           -- PPT (Availability denominator)
  operating_time_min        NUMERIC NOT NULL DEFAULT 0,
  planned_downtime_min      NUMERIC NOT NULL DEFAULT 0,
  unplanned_downtime_min    NUMERIC NOT NULL DEFAULT 0,
  -- count quantities
  total_count               NUMERIC NOT NULL DEFAULT 0,
  good_count                NUMERIC NOT NULL DEFAULT 0,
  ideal_cycle_time_sec      NUMERIC,                              -- the denominator used (provenance)
  -- derived factors (persisted for serving; always re-derivable)
  availability              NUMERIC CHECK (availability  >= 0),
  performance               NUMERIC CHECK (performance   >= 0),
  quality                   NUMERIC CHECK (quality       >= 0),
  oee                       NUMERIC CHECK (oee           >= 0),
  teep                      NUMERIC CHECK (teep          >= 0),
  fidelity                  oee.capture_fidelity NOT NULL DEFAULT 'MANUAL',
  computed_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  ext                       JSONB NOT NULL DEFAULT '{}'::jsonb,
  CHECK (bucket_end >= bucket_start),
  CHECK (good_count <= total_count),
  UNIQUE (tenant_id, work_unit_ref, grain, bucket_start)
);
CREATE INDEX ix_oee_interval_serve ON oee.oee_interval (tenant_id, work_unit_ref, grain, bucket_start DESC);
COMMENT ON TABLE oee.oee_interval IS 'Computed OEE per asset x time bucket; stores time/count QUANTITIES so roll-ups sum-then-divide (no averaging of %, deep-plan §4).';

-- ---------------------------------------------------------------------
-- 7. Loss attribution — the loss tree leaves (Six Big Losses), priced.
-- ---------------------------------------------------------------------
CREATE TABLE oee.loss_attribution (
  loss_attr_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id                 UUID NOT NULL,
  oee_interval_ref          BIGINT NOT NULL REFERENCES oee.oee_interval(oee_interval_id) ON DELETE CASCADE,
  big_loss                  oee.big_loss NOT NULL,
  oee_component             oee.oee_component NOT NULL,
  loss_category_ref         BIGINT REFERENCES canon.loss_category(category_id),
  reason_ref                BIGINT REFERENCES canon.reason_code(reason_id),
  downtime_event_ref        BIGINT REFERENCES canon.event(event_id),   -- shared event (no double count w/ M2)
  lost_minutes              NUMERIC NOT NULL DEFAULT 0,
  lost_units                NUMERIC NOT NULL DEFAULT 0,
  lost_cost                 NUMERIC,                              -- priced via canon.cost_rate (D7 rate-as-of)
  cost_rate_ref             BIGINT REFERENCES canon.cost_rate(rate_id),
  ext                       JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX ix_loss_attr_interval ON oee.loss_attribution (tenant_id, oee_interval_ref);
CREATE INDEX ix_loss_attr_reason ON oee.loss_attribution (tenant_id, reason_ref);
COMMENT ON TABLE oee.loss_attribution IS 'Per-interval decomposition into the Six Big Losses by reason, with minutes/units/cost (deep-plan §6).';

-- ---------------------------------------------------------------------
-- 8. Top-loss Pareto snapshot — ranked by minutes AND by cost (§6).
-- ---------------------------------------------------------------------
CREATE TABLE oee.top_loss (
  top_loss_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id                 UUID NOT NULL,
  scope_node_ref            BIGINT REFERENCES canon.equipment_node(node_id),   -- asset/line/plant scope
  period_start              TIMESTAMPTZ NOT NULL,
  period_end                TIMESTAMPTZ NOT NULL,
  rank_basis                oee.rank_basis NOT NULL,
  rank                      INT NOT NULL CHECK (rank > 0),
  big_loss                  oee.big_loss,
  reason_ref                BIGINT REFERENCES canon.reason_code(reason_id),
  value                     NUMERIC NOT NULL,                     -- minutes / cost / units per rank_basis
  is_other_bucket           BOOLEAN NOT NULL DEFAULT FALSE,       -- governance flag: 'All Other' in top-loss (§6)
  computed_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  ext                       JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX ix_top_loss_scope ON oee.top_loss (tenant_id, scope_node_ref, period_start DESC, rank_basis, rank);
COMMENT ON TABLE oee.top_loss IS 'Pareto cache of biggest losses by minutes and by cost; flags an over-sized "All Other" bucket for refinement (deep-plan §6).';

-- ---------------------------------------------------------------------
-- 9. Policy change log — effective-dated definition changes (audit).
--    Changing a definition moves the number, so it must be trend-visible (§13).
-- ---------------------------------------------------------------------
CREATE TABLE oee.policy_change_log (
  policy_change_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id                 UUID NOT NULL,
  changed_what              TEXT NOT NULL,                        -- e.g. 'micro_stop_threshold_sec','ideal_cycle','planned_time_convention'
  work_unit_ref             BIGINT REFERENCES canon.equipment_node(node_id),
  old_value                 TEXT,
  new_value                 TEXT,
  changed_by                TEXT NOT NULL,
  changed_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  effective_from            TIMESTAMPTZ NOT NULL,
  ext                       JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX ix_policy_change ON oee.policy_change_log (tenant_id, changed_at DESC);

-- ---------------------------------------------------------------------
-- 10. Readiness snapshot (M4 view of the platform readiness model, §11).
-- ---------------------------------------------------------------------
CREATE TABLE oee.readiness_snapshot (
  readiness_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id                 UUID NOT NULL,
  work_unit_ref             BIGINT NOT NULL REFERENCES canon.equipment_node(node_id),
  gate                      oee.readiness_gate NOT NULL,
  score                     NUMERIC CHECK (score BETWEEN 0 AND 100),
  passed                    BOOLEAN NOT NULL DEFAULT FALSE,
  detail                    TEXT,
  computed_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  ext                       JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX ix_readiness ON oee.readiness_snapshot (tenant_id, work_unit_ref, gate);
COMMENT ON TABLE oee.readiness_snapshot IS 'Per-asset readiness incl. M4 Fidelity gate (manual vs auto, micro-stops, ideal calibrated) and History gate for prediction (deep-plan §11).';

-- ---------------------------------------------------------------------
-- 11. FUTURE SCOPE — prediction interface stub (no v1 build, §8).
-- ---------------------------------------------------------------------
CREATE TABLE oee.loss_prediction (
  loss_prediction_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id                 UUID NOT NULL,
  work_unit_ref             BIGINT NOT NULL REFERENCES canon.equipment_node(node_id),
  big_loss                  oee.big_loss,
  predicted_for             TIMESTAMPTZ,
  probability               NUMERIC CHECK (probability BETWEEN 0 AND 1),
  model_version             TEXT,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  ext                       JSONB NOT NULL DEFAULT '{}'::jsonb
);
COMMENT ON TABLE oee.loss_prediction IS 'FUTURE-SCOPE stub (deep-plan §8): populated only when prediction is built and the History gate passes. Shares M2 OSA-CBM substrate.';

-- ---------------------------------------------------------------------
-- 12. Serving view — roll up by SUMMING quantities, THEN dividing.
--     Demonstrates the no-average rule structurally (§4).
-- ---------------------------------------------------------------------
CREATE VIEW oee.v_oee_rollup AS
SELECT
  tenant_id,
  work_unit_ref,
  date_trunc('day', bucket_start)                                   AS day,
  SUM(planned_production_min)                                       AS ppt_min,
  SUM(operating_time_min)                                           AS operating_min,
  SUM(total_count)                                                  AS total_count,
  SUM(good_count)                                                   AS good_count,
  CASE WHEN SUM(planned_production_min) > 0
       THEN SUM(operating_time_min) / SUM(planned_production_min) END AS availability,
  CASE WHEN SUM(operating_time_min) > 0
       THEN (SUM(total_count) * MAX(ideal_cycle_time_sec) / 60.0) / SUM(operating_time_min) END AS performance,
  CASE WHEN SUM(total_count) > 0
       THEN SUM(good_count) / SUM(total_count) END                  AS quality
FROM oee.oee_interval
GROUP BY tenant_id, work_unit_ref, date_trunc('day', bucket_start);
COMMENT ON VIEW oee.v_oee_rollup IS 'Daily OEE roll-up computed by summing quantities then dividing — never by averaging interval percentages (deep-plan §4).';
